### ISSUE TITLE
Testing Websocket APIs

### ISSUE THREAD

**Issue by CMCDragonkai** [Codeception/Codeception#1082]
Is there anyway for Codeception to test websocket APIs?

**Comment by anders-akero** [comment]
Have anyone been working on an implementation for websocket testing? I can not see that anyone started on a branch for this?
Maybe I can help out if someone has started with this and are willing to share what they have done so far.
I'm using PhanomJS as browser for testing in codeception as my application uses a lot of javascript. It would be very good to be able to test connections via websocket as well.
I believe that websockets will be used more and more and having a way to test this would improve codeception a lot.

**Comment by DavertMik** [comment]
Unfortunately we don't have this done. But I'd like to have WebSockets done, for me it like Next Gen protocol and it needs to be tested

**Comment by kurbar** [comment]
@DavertMik Recently I was in need of such module for some tests on our own project and I started creating a WebSocket module as well. Currently the limitation of it is that it operates with WAMP v1 since that was the requirement for me and I'm implementing it for Codeception v1.8 (but can be upgraded for recent version as well).

I have finished my first version of it (currently writing docs for the module) so if you wish, I can create a PR for it here..

**Comment by DavertMik** [comment]
@kurbar sounds interesting. At least I'd really like to take a look on it. But I according to your words it will require extra work... Anyway, please send PR but to 2.2 branch as 1.x is not maintained anymore

**Comment by nnrudakov** [comment]
@DavertMik , have you any news about this enhancement?

**Comment by Naktibalda** [comment]
Since 4.0 Codeception modules are separated from core and have their own repositories, this reduced differences between core modules and third party modules.
If someone really needs this module they can implement it by themselves and publish it to Packagist.
There are no plans to implement such module.
