### ISSUE TITLE
$I->click method doesn't work/throwing exception

### ISSUE THREAD

**Issue by tad3j** [Codeception/Codeception#1191]
In my functional test (ZF2 module) I'm trying to submit a form and all goes well until I try to click the submit button with `$I->click('Sign In');´ . I'm getting this result:

    Sorry, I couldn't click "Sign In":
    ErrorException: array_replace(): Argument #2 is not an array

    Scenario Steps:
    6. I click "Sign In"
    5. I see "Sign In",
    ...

Because of the exception I tried to provide an empty array as 2nd parameter, but the same happens. For just in case I've tried with more advanced selectors but I'm not able to get pass this point. Any idea why this is happening?

**Comment by Naktibalda** [comment]
array_replace is not used anywhere in the source code of Codeception.
My prime suspect is BrowserKit and there is only one occurrence of array_replace

https://github.com/symfony/BrowserKit/blob/de4f2ed1f3c11ba5d4b6ec5aa7e0cc5454f0ca00/CookieJar.php#L210
$parts = array_replace(array('path' => '/'), parse_url($uri));

On seriously malformed URLs, parse_url() may return FALSE. 


A few uri related issues have been fixes in BrowserKit Client since this issue had beed reported.

Commits on Jul 25, 2014 
Fixed server HTTP_HOST port uri conversion

Commits on Aug 5, 2014 

[BrowserKit] Fix browser kit redirect with ports
Fixed relative redirects for ambiguous paths


To investigate this issue any further I need a target url of the form and url of redirection (if any).
