### ISSUE TITLE
_reconfigure not works as expected in WebDriver

### ISSUE THREAD

**Issue by pablopaul** [Codeception/Codeception#1192]
http://codeception.com/docs/06-ModulesAndHelpers#Runtime-Configuration suggests

``` terminal
Runtime Configuration
If you want to reconfigure module in run time, you can use the _reconfigure method of the module. You may call it from helper class and pass in all the fields you want to change.
```

``` php
<?php
$this->getModule('WebDriver')->_reconfigure(array('browser' => 'chrome'));
?>
```

but this is not changing anything when called from a helper class (too late to configure browser), when the helper class is loaded the browser is already launched.

See #1188 for more details.

**Comment by kpascal** [comment]
was this ever resolved? Running into this right now and not sure if its a setup issue. Thanks!

**Comment by pablopaul** [comment]
@DavertMik any news for @kpascal ? ;)

**Comment by rzmz** [comment]
Still not working?

**Comment by dlfxhappy** [comment]
I'm experiencing the same issue. As a quick workaround I used _setConfig which work just as well. 
It seems like _resetConfig() is triggered by the EventSubscriber Module class right before each test, resetting the runtime configuration. It was  introduced [here] (https://github.com/Codeception/Codeception/commit/1fe7550b3bf14b9f5c49b6632bf58f72ff9642bc#diff-f289a837c8f665dd8961f02aac33134f). If removing that line turns out to be a bad idea, the documentation should state that module reconfiguration is only temporary and has to be done in the _before method for each test run.

**Comment by gunfrank** [comment]
So is there a workaround to reconfigure WebDriver at the start of a Cept, before the actual browser instance is spawned?

**Comment by Darhazer** [comment]
In the case of changing the browser type, as the capabilities are already negotiated, you have to quit the already launched browser and launch a new one
```php
$webDriver->_setConfig($config);
$webDriver->webDriver->quit();
$webDriver->_initialize();
```
Interestingly enough, webDriver provides public function `_initializeSession` that starts new browser instance, but do not allow to override it's capabilities.

**Comment by FelikZ** [comment]
@Darhazer this function is used by haveFriend, and unfortunately yes, it is not populated...

**Comment by FelikZ** [comment]
https://github.com/Codeception/Codeception/blob/2.2/src/Codeception/Module/WebDriver.php#L1130

Why not to just use `_initialize()`? Anyone knows?

**Comment by GoelNupur** [comment]
any updates on this @Naktibalda

**Comment by Naktibalda** [comment]
It seems very straightforward to fix.
