### ISSUE TITLE
Recommend installing Codeception globally

### ISSUE THREAD

**Issue by samdark** [Codeception/Codeception#1238]
There was a discussion at #1025. I've actually tried it and it works very well. If you have Composer global `bin` directory in `PATH` you can call Codeception just as `codecept` from anywhere. That lowers confusion about quite lengthy commands when running it from `vendor`. Especially if your apps are deep into subdirectories.

Global installation is recommended for PHPUnit and works very well alongside Codeception.

I think it's safe to recommend such approach in docs instead of current per-project one.

**Comment by zbateson** [comment]
My one concern with this is it may discourage including codeception as a dependency for an application's "require-dev", which I think is important... especially because it allows each application to define not only the fact that it uses codeception for its testing but also because it allows it to specify what version.

I think recommending that should be the key... so for instance if you're dependent on version 2.0, you should have "codeception/codeception": "~2.0.0".  If you rely on a specific feature introduced in 2.0.11 you should use ^2.0.11, etc...

If you end up getting used to calling 'codecept' rather than './bin/codecept' or 'php bin/codecept', you run the risk of running a version of Codecepttion not intended for the application.  What are your thoughts?

**Comment by DavertMik** [comment]
I agree to @zbateson points. This may also be important because of 2.1 release
There is also one **major** issue, which should be taken into account. Codeception installs globally its dependencies which are PHPUnit and Guzzle. And those two can get in conflict with already installed PHPUnit and maybe Guzzle.

**Comment by zbateson** [comment]
Yeah, if possible I would recommend installing PHPUnit and Guzzle locally instead of globally.  I'm not sure why they were originally configured as global but it makes much more sense to me for them to be local.

Especially when you think how Codeception's PHPUnit dependency (not sure about Guzzle) seems very version-specific but IIRC moves up even in minor releases.

**Comment by DavertMik** [comment]
composer install global is a modern way to say `pear install phpunit ` =)
