### ISSUE TITLE
codeception run only one test from a class

### ISSUE THREAD

**Issue by tzookb** [Codeception/Codeception#1261]
how can I run only one test from my tests class,
this is how I run only that class file:

```
codecept run tests/acceptance/VisitorCest.php
```

and here is a link to stackoverflow question:
http://stackoverflow.com/questions/25074243/codeception-run-only-one-test-from-a-class

**Comment by dynasource** [comment]
for those who want to know how to execute a single test only in case of multiple methods starting with the same name:

* append $

So instead of:
```php
$ php codecept.phar run tests/acceptance/ItemCest:create
```

which is running:
* ItemCest:create
* but also ie. ItemCest:createByMe and ItemCest:createMultiple

```php
$ php codecept.phar run tests/acceptance/ItemCest:create$
```

Davert, this is something to put in:
* http://codeception.com/docs/02-GettingStarted#Running-Tests

Also, http://codeception.com/docs/reference/Commands is too little documented on the Run command. IMHO, this deserves most attention, far more than the Generate method which are put at top of that page.
