### ISSUE TITLE
Codeception exit code breaking CI Automation on 'failed tests'

### ISSUE THREAD

**Issue by precariouspanther** [Codeception/Codeception#14]
In Codeception/Command/Run::execute() on line 66:
`if ($codecept->getResult()->failureCount() or $codecept->getResult()->errorCount()) exit(1);`

Codeception is exiting with a status code of "1" whenever any of the tests fail. This confuses CI frameworks like Bamboo (and presumably jenkins) into thinking that codeception itself failed.

Ideally even when errors have been detected the exit code should still be "0" so that CI frameworks know that Codeception executed the tests correctly, and then parse the results to see which tests failed or succeeded.

Thanks :)

**Comment by Robdebert** [comment]
There might also be a problem with bitbuckets CI-pipelines.
The pipeline returns "ok" (green), although Codeception found errors.

I guess bitbucket pipelines are testing, if anything returns 2 and otherwise everything is ok for them.

Could there also be an option to set the exit-code to 2 instead of 1? Something like "--convert_warnings_to_errors" ?
