### ISSUE TITLE
One runner for multiple Applications fails on unit tests

### ISSUE THREAD

**Issue by eddiejaoude** [Codeception/Codeception#1404]
Works fine for Acceptance & Functional Tests, but Unit Tests fail with class not found.

Using ZF2.
`tests/` works fine
`module/Application/tests` does not work for unit tests

**Comment by haclong** [comment]
i think i have the same issue though i got this error message in console :
Failed to try to test in {namespace}\{testCest}::tryToTest (path/to/testfile)

The error message is not very readable though and i can't understand what's wrong.

I am using ZF2 (ZF2 Skeletton Application)
I have bootstrapped a codeception projet in the main ZF2 application
The ZF2 projet has two modules (in module/)
i have done : php codecept.phar bootstrap --namespace module_name module/ModuleName - once per module
I have added Mockery and ZF2 module in each unit.suite.yml

Somehow, i can't run unit test suites properly and no clear error message are returned.

**Comment by haclong** [comment]
i have reinstalled the full suite(s) and build each time i'm changing a line in any files... it is now working though i don't know why and what i have done different from previous attempts. I still think this is not stable hence not really satisfactory

**Comment by seaneble** [comment]
I encounter the same problem.
I have set up my tests with Codeception so that acceptance tests are done over the whole ZF2 project. The project is split up in several modules which provide their own unit tests.
All tests are run from one command.

Unit testing the ZF2 modules does not work properly. For one thing, I had to extend the `application.config.php` to search for modules two directory levels up (../../modules) because the path is not relative to the project root but relative to each Codeception instance.

Now my modules are at least loaded, but their respective configuration isn't. It seems running the whole Application from a single module does not work because the paths are all off by two levels.

If I move the tests to the main test configuration, everything is fine.

**Comment by eXorus** [comment]
Thank you for contributing to this issue. As it has been 4 years since the last activity, we are automatically closing the issue. This is often because the request was already solved in some way and it just wasn't updated or it's no longer applicable. If that's not the case, please feel free to either reopen this issue or open a new one. 

The new repository for ZF2 is https://github.com/Codeception/module-zf2.

We will be more than happy to look at it again!
