### ISSUE TITLE
generate scenarios ignores "common" functions

### ISSUE THREAD

**Issue by codeasaurus** [Codeception/Codeception#1432]
I am making heavy use of Common classes to categorize reusable test components. I have this acceptance test:

```php
public function CreateManualTimeEntryToday(AcceptanceTester $I, $scenario)
{
    $I->wantTo('Create Manual Time Entry For Current Day');
    DashboardCommon::seeDashboard($I);
    NavCommon::switchWorkspace($I, 'QAPT Trucking');
    DashboardCommon::createBasicManualTimeEntry($I);
}
```

running `php codecept g:scenarios acceptance` produces a file that contains only:

```
I WANT TO CREATE MANUAL TIME ENTRY FOR CURRENT DAY
```

Stepping through the code it's obvious why. How useful are the human-readable scenarios if the parser doesn't step through the entire call stack? If the customer requires the scenario documents, that means I can't use Common classes. Using Steps seems to work for this, but Steps classes have their own set of problems which are making them unusable for me.

On a side note, the parser fails miserably if I choose to name the AcceptanceTester instance anything but `$I`, because `$I->` is hard-coded into the regular expressions.

**Comment by LowellMontgmery** [comment]
> I really like the concept of steps, and I really don't like the idea of
implementing yet another way of doing things. But I think steps should have
been implemented as trait types, rather than extending the actor. That
would have solved the clutter in my high-level tests, as well as eliminate
the requirement to have access to $scenario (which I don't have in the
_before/_after/_[etc] functions.

I absolutely agree... I didn't even realize steps were not implemented as traits till I went to use them in my second trial "acceptance" test and was thinking: "Hmm... this isn't going to be so pretty, after all...".

I don't need to create users, give them special permissions, or use those users to create (various kinds of) complex content, or edit such content in *every* test, but I *do* need to perform at least some basic "common functionality" of some kind in every test, so it makes sense to just have traits to neatly organize and load that extra functionality where we need it. Reading [Michael Bodnarchuk's plan for this](https://github.com/Codeception/Codeception/pull/1228#issuecomment-49668483), makes me think I need to change our composer.json file to use the (not-yet-stable) Codeception 2.1 as the basis of the massive refactoring we are about to do on a number of "legacy" integration test suites (mainly Selenium setups with PHPUnit/Selenium -based tests). I'm more and more happy with Codeception. I think using it will make better coders of our team members.
