### ISSUE TITLE
How can I access an actor (e.g. AcceptanceTester) in a Codeception helper

### ISSUE THREAD

**Issue by ElRakiti** [Codeception/Codeception#1443]
Since I can't find anything in the documentation or in the source-code, I have the following question:

When I use the AcceptanceHelper generated by codeception (_support/AcceptanceHelper.php), how can I access the Actor / AcceptanceTester ($I). And how can I access my functions from StepObjects?

I have:

acceptance/_steps/MyStepObject.php

namespace AcceptanceTester;

```
class MyStepObject extends \AcceptanceTester
{
public function deleteCookies(){
$I = $this;

$I->amGoingTo("delete all cookies...");
$I->executeInSelenium(function(\WebDriver $webdriver) {$webdriver->manage()->deleteAllCookies(); });
$I->reloadPage();
}

public function loginUser($user,$password,$language = 'Untranslated')
{
$I = $this; 

$I->amOnPage(\LoginPage::$URL);
$I->deleteCookies();
$I->amGoingTo('fill the fields...');
$I->fillField(\LoginPage::$usernameField, $user);
$I->fillField(\LoginPage::$passwordField, $password);
$I->click(\LoginPage::$loginButton);
}   
}
```

In the class _support/AcceptanceHelper.php I want to call methods from the AcceptanceTester like $I->canSee('something') and I want to call my own methods (like 'login') from my StepObject.

I know I can get a specific module (e.g. the WebDriver) with $this->getModule('WebDriver'). But how can I get the AcceptanceTester / my StepObject?

Thanks!

**Comment by Suseika** [comment]
@DavertMik 
> they are for implementing custom testing actions, not for grouping them.

Then what is for grouping actions? Say I want to do:
```php
$I->amOnPage("very long line with $changing $parameters");
$I->see("something");
```
several times and with different parameters?

**Comment by Naktibalda** [comment]
@Suseika Action grouping can be implemented using [Step objects](http://codeception.com/docs/06-ReusingTestCode#StepObjects).

But what you actually want is Data Providers in Test format and [Examples](http://codeception.com/docs/07-AdvancedUsage#Examples) in Cept format.

**Comment by Suseika** [comment]
@Naktibalda Thanks, I'll look into that.

**Comment by Jacek-fstack** [comment]
Hey, I have a problem - what approach do I use if I want to group my actions?
I know there are stepObjects, but these are only to extend certain functionality, as far as I understand. 
How would I go about grouping actions like
AccountHelper - for registering a new account, logging in actions
BillingHelper - for handling billing related stuff etc.
BUT
I want to be able to call from the helpers all Actor actions, so
`$user = $this->getModule('Webdriver');
        $user->amOnPage('/admin/user/login');
        $user->click('.registerLink');`
When I use this from my AccountHelper class, only the amOnPage gets executed, and it passes, nothing after that is executed and it passes. I am assuming it's because click is handled by actor class?
So how do I group my actions so not everything is in the WebGuy class?

**Comment by Naktibalda** [comment]
@Jacek-fstack it is probably better to open a new ticket.

Your question is confusing - it looks like 2 issues mixed together - something about using multiple helpers and that click is not executed as expected.
Example of test and output of test executed with --steps flag would help to understand your issue.
