### ISSUE TITLE
is codeception wait for the record to be inserted in the database or not?

### ISSUE THREAD

**Issue by ghost** [Codeception/Codeception#1540]
i have this wierd situation:

i create a new envirement, and this is the configuration am using:
- laravel, from the command line: laravel new website_name
- codeception using composer: composer require codeception/codeception

am using the functional cest format
![cest](https://cloud.githubusercontent.com/assets/8344845/5076561/d0787d60-6e93-11e4-8918-558b58a09841.png)

this is the route:
![route](https://cloud.githubusercontent.com/assets/8344845/5076564/d8fc5e5c-6e93-11e4-9050-ac487b0eeb70.png)

am using both the modules Laravel4 and Db, i already configured the Db module on codeception.yml like so
![db](https://cloud.githubusercontent.com/assets/8344845/5076368/5cbc15d6-6e92-11e4-89da-be505eb71773.png)

i also make a dump of mysql database to tests/_data/dump.sql

when i refresh the web browser, the record is inserted in the database, but when i test using codeception, i get this
![issue](https://cloud.githubusercontent.com/assets/8344845/5076613/43d9b79c-6e94-11e4-9d85-de41f14cad11.png)

but when i change the value of title in seeInDatabase, to match the one from haveInDatabase, i get a success, it look like codeception functional test doesn't look at the database for the updated value, i have no clue of what is going on, it already took me more than 5 hours, before posting this issue, trying to figure out what the heck is this !!

any clue?

**Comment by elarichev** [comment]
You can write custom method in your helper class.
For example
```
public function waitRecordInDatabase($table, array $criteria, $timeout = 10)
{
    /** @var Db $dbModule */
    $dbModule = $this->getModule('Db');
    for ($i = 0; $i < $timeout; $i++) {
        try {
            $dbModule->seeInDatabase($table, $criteria);
        }
        catch (Exception $e) {
            sleep(1);
            continue;
        }
        return true;
    }
    throw new Exception("Waited for $timeout seconds but record " . json_encode($criteria) . ' still not found in DB');
}
```

**Comment by SamMousa** [comment]
@elarichev I have locked this conversation as it was 4 years old.

Your piece of code only makes sense in specific cases and people should take care not to carelessly use it.
Due to the fact that PHP is single threaded, when running functional tests, the database records will always be written before the assertion is made.
In case of acceptance tests Codeception waits for the page to load, which in almost all cases means the database records have already been committed by the server side code before your assertions are run.
If you have an issue / suggestion feel free to create a new issue.

Regardless, thanks for your contribution to the community!
