### ISSUE TITLE
[Question] How should routing be handled when generating acceptance test coverage in Laravel 4?

### ISSUE THREAD

**Issue by bkuhl** [Codeception/Codeception#1643]
I'm attempting to use acceptance tests to generate code coverage on my controllers.  I've followed the instructions outlined in the [coverage documentation](http://codeception.com/docs/11-Codecoverage).

I'm receiving the following error when running `codecept run acceptance`:
```
[PHPUnit_Framework_Exception] file_get_contents(http://mySite.dev/c3/report/clear): failed to open stream: HTTP request failed! HTTP/1.0 500 Internal Server Error
```

My **index.php** contains the following.  I've verified this path is correct. 
```php
base_path('c3.php');

$app->run();
```

The Laravel logs are indicating that Laravel doesn't have a route for this address and thus doesn't know how to handle it...
```
[2015-01-14 17:07:54] local.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/apps/myApp/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:148
```

**Is there some custom routing or special config that is necessary to generate coverage in a Laravel application?**  Any advice/guidance would be much appreciated.

**Comment by janhenkgerritsen** [comment]
I implemented code coverage for the [sample Laravel 4 application](https://github.com/Codeception/sample-l4-app). I got it working, but not very stable. Sometimes everything works as expected, but sometimes there are random errors. These mostly seem to occur if you run tests with remote code coverage too fast after each other. Code coverage for functional and unit tests works just fine. 

Code coverage is a hard topic because it involves many things, so if things go wrong you can never easily determine what is going wrong. There can be an issue with Xdebug, or with file permissions or something else entirely. That said, I will give you some pointers about things I ran into while setting op code coverage. 

For the configuration you can take a look at the sample application. The `c3.php` file should be located in your applications root directory and you should include the file in your `public/index.php` file with the following statement: `include '../c3.php`.

* Make sure you have `xdebug.remote_enable=1` in your Xdebug configuration
* Code coverage files are written to the `tests/_output` directory so make sure the permissions are correct
* You can try to delete all files in the `_output` directory before you run tests with code coverage
* Don't run tests with code coverage to fast after each other, wait something like 10 or 15 seconds between runs.
* The error I got a lot was `file_get_contents(http://l4.app/c3/report/clear): failed to open stream: HTTP request failed!`. I just deleted everything from the `_output` directory, and after that the tests worked again most of the time.
* Look in the log files of Laravel and your webserver to check if there are errors.

Hope this helps!
