### ISSUE TITLE
Functional Tests refuse to fillField.

### ISSUE THREAD

**Issue by jarrettj** [Codeception/Codeception#1689]
I'm not quite sure why my functional tests refuse to fill a field.

My functional.suite.yml:

```
class_name: TestGuy
modules:
    enabled: 
        - TestHelper
        - ZF2
    config:
        ZF2:
          config: 'config/application.config.php'
```

My login test:
```
$I = new TestGuy($scenario);
$I->amOnPage('/');
$I->fillField('identity', $username);
$I->fillField('credential', $password);
$I->submitForm(".form-signin", array());
```

The verbose output is:
```
php vendor/bin/codecept run functional -vvv
Codeception PHP Testing Framework v2.1.0
Powered by PHPUnit 4.4.5 by Sebastian Bergmann.

Functional Tests (2) ---------------------------------------------------------------------------------------------------------------------
Modules: TestHelper, ZF2
------------------------------------------------------------------------------------------------------------------------------------------
1stLoginCept 
Scenario:
* I am on page "/"

  [Response] 200
  [Page] http://localhost/user/login
  [Cookies] []
  [Headers] {"Location":"/user/login"}
* I fill field "identity","admin-user@naspers.com"
* I fill field "credential","password"
* I submit form ".form-signin",
  [Uri] http://localhost/user/login
  [Method] post
  [Parameters] {"identity":"","credential":""}
  [Response] 200
  [Page] http://localhost/user/login
  [Cookies] []
  [Headers] {"Location":"/user/login"}
* I see in current url "/"
 PASSED 

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Create an admin user. (Application/AdminUser/CreateCept) 
Scenario:
 PASSED 

------------------------------------------------------------------------------------------------------------------------------------------
```

The fields are found, but nothing is posted when the form gets submitted. Has anyone had this issue with ZF2 and codeception before? 

Any help would be appreciated. Thanks.

**Comment by zbateson** [comment]
Hi @jarrettj 

I'm not entirely certain without testing it, whether or not setting fillField actually updates the value attribute of the field itself - you could test with grabValueFrom('identity') after calling fillField and see if it's actually set.  Normally fillField is used with click() instead of submitForm (again just from what I've seen and am remembering).  If you need to use fillField, I would recommend calling click on a submit button.

The alternative if you'd rather use submitForm is to send the value of the form fields in the second argument instead of the empty array ```$I->submitForm('.form-signin', ['identity' => 'admin-user@naspers.com', 'credential' => 'password']);```
