### ISSUE TITLE
Laravel 5 Module: Special Characters are not found by $I->see

### ISSUE THREAD

**Issue by Sopamo** [Codeception/Codeception#1759]
$I->see("Straße")
does not work (that is the german word for "street"). When I change the test and the corresponding site to:

    $I->see("Strasse")

it works fine. That was working fine in the Laravel4 Module.

**Comment by Sopamo** [comment]
I've got some more info on this:
Seems like something changed with how these special characters are treated.

This works:

    $I->see("Stra&szlig;e");
    $I->click("Straße");

I think The ->see method uses the Laravel output (which is converting ß to &szlig;) internally. Not sure if that was already the case with Laravel 4.
But the ->click Method seems to use some other content where the ß is not converted. This is really confusing and I imagine that many german developers will have problems with this. I'm not sure if it's a good idea to change anything in Codeception because that might be an issue of the symfony DOM crawler.
Nevertheless we should at least mention this "issue" in the docs.

**Comment by janhenkgerritsen** [comment]
I have created a view and a new test in the sample application, but there does not seem to be a problem. I cannot update the sample application on Github yet because that will break the overall Codeception build due to another bug, but the code is as follows:

```
// View

@extends('layouts.scaffold')

@section('main')
    <p class="character">Straße</p>
    <p class="html-encoded">Stra&szlig;e</p>
    <a class="character" href="#">Straße</a>
    <a class="html-encoded" href="#">Stra&szlig;e</a>
@stop
```

```
// Test

<?php 
$I = new FunctionalTester($scenario);
$I->wantTo('test for text that uses special characters');

$I->amOnPage('/special-characters');

$I->see('Straße', 'p.character');
$I->see('Straße', 'p.html-encoded');

$I->click('Straße', 'a.character');
$I->click('Straße', 'a.html-encoded');
```

Does this test cover your issue or am I missing something?

The Laravel4 and Laravel5 module use the same methods for both the `click()` and `see()` methods, and these methods are implemented by the `Codeception/Lib/InnerBrowser` class from which both modules inherit. These methods are also used by other modules for other frameworks, for example Symfony, Zend Framework, etc.

Are you maybe using some other module that overrides the `see()` or `click()` methods?

And as a last question, what charset does your HTML output specify? The sample app uses UTF-8, maybe you use something different?

**Comment by Sopamo** [comment]
Thanks for looking into this. I just found out the another important bit which I oversaw earlier.
The issue only happens when checking for text in input fields (in the value attribute). I realized there is a seeInField method which does work. More info:

    // View

    @extends('layouts.scaffold')

    @section('main')
        <form>
            <input name="special-encoded" value="Stra&szlig;e">
            <input name="special" value="Straße">
        </form>
    @stop

-
    // Test
    <?php 
    $I = new FunctionalTester($scenario);
    $I->wantTo('test for input fields which use special characters');

    $I->amOnPage('/special-characters');

    $I->see("Straße"); // Works
    $I->see("Stra&szlig;e"); // Works

    //$I->see("Straße",'form'); // Fails - I would expect this to work as well
    //$I->see("Stra&szlig;e",'form'); // Fails - Is ok I guess

    $I->seeInField('input[name="special"]',"Straße"); // Works
    $I->seeInField('input[name="special"]',"Stra&szlig;e"); // Fails - Is ok I guess

    $I->seeInField('input[name="special-encoded"]',"Straße"); // Works
    $I->seeInField('input[name="special-encoded"]',"Stra&szlig;e"); // Fails - Is ok I guess

Encoding is UTF-8 as well for me. As the ```see``` method does work for non special characters in input fields I would expect it to work for special characters as well.

**Comment by janhenkgerritsen** [comment]
If you use `$I->see()` without a selector argument it treats the response as a string and searches for an exact match. This explains why your first two tests work.

If you use `$I->see()` with a selector argument it uses the `DomCrawler` component, which matches nodes and tests againts the `DOMElement->nodevalue` property. The DOM component translates the HTML encoded characters into their actual characters. This means it does not test against text in the HTML elements themselves, for example arguments and their values. With this knowledge the results of your other tests can be explained. 

I would also argue that this behavior is correct, because I think you should not be testing with the `Stra&szlig;e` string if you can use the actual character in your test.

**Comment by Sopamo** [comment]
Okay, you might be right with arguing that the tests are behaving correctly - or at least that it would be difficult to work around this behavior. As a programmer writing tests I would intuitively expect all of my tests to pass so I think we should add some notes about special characters to the docs. I talked to two other (german) programmers who had the same issue and I was the first to tell them why and how to solve it.
Should I submit a pull request to add a sentence to the docs about special characters?

**Comment by janhenkgerritsen** [comment]
Yes, submitting such a pull request is probably the best option. Make sure you add it to the general Codeception docs though, since this is not a Laravel specific issue.
