### ISSUE TITLE
Module/SOAP with Symfony2 Framework

### ISSUE THREAD

**Issue by Noles** [Codeception/Codeception#1784]
I configured Codeception with 
```
class_name: ApiTester                                                                                                                                             
modules:
    enabled: [Symfony2, SOAP, ApiHelper]
```

In my opinion the code in Module/SOAP.php::processInternalRequest does not make sense for the use of the Symfony2 Framework.

Why should the symfony2 output be catched via output buffer? The internal response from symfony is a Symfony\Component\HttpFoundation\Response class.

A return for $this->client->getInternalResponse()->getContent() should be the better choice.

Or do I miss something?

Thanks.
Noles

**Comment by DavertMik** [comment]
I can't say for sure, as this module was written by me and tested with Symfony v2.1
There were reasons to do things exactly this way few years ago. If you see there is a more optimal way now, please try it on your project and send a pull request. 

Probably, this output buffer thing was because of SOAP library had its own output... But I can't say for sure. That was long ago )
