### ISSUE TITLE
Cleanup will fail if Doctrine EntityManager is change dynamically

### ISSUE THREAD

**Issue by hserge** [Codeception/Codeception#1804]
Lets say we have a test where we use Doctrine2 module. In the test, If I change entity manager by assigning a new value to the static $em parameter of the module, then cleanup functionality fails, because transaction was initiated with another em and separate transaction handling must be implemented in the test.

I cannot find any decent way to change it before Doctrine2 module initialization to make cleanup functionality work as expected.

**Comment by eXorus** [comment]
Thank you for contributing to this issue. As it has been 5 years since the last activity, we are automatically closing the issue. This is often because the request was already solved in some way and it just wasn't updated or it's no longer applicable. If that's not the case, please feel free to either reopen this issue or open a new one. 

The new repository is: https://github.com/Codeception/module-doctrine2

We will be more than happy to look at it again!
