### ISSUE TITLE
@depends parameter passing in Cest classes

### ISSUE THREAD

**Issue by nkovacs** [Codeception/Codeception#1829]
With the normal phpunit test classes, you can get the return value of a dependency like this:

```php
public function testFoo()
{
    return 'foo';
}

/**
 * @depends testFoo
 */
public function testBar($foo)
{
    verify($foo)->equals('foo');
}
```

How do I do this with Cest classes? It's not documented [here](http://codeception.com/docs/07-AdvancedUsage#Depends-Annotation).

**Comment by ashnazg** [comment]
I don't think that Codeception's depend annotation functions in the same manner as PHPUnit's.  Codeception's seems to only concern itself with pass status of one testcase method affecting whether or not a second testcase method gets run or skipped.  PHPUnit's seems to also act this way, but only as a coincidental side effect... it _requires_ some artifact of the first testcase to be passed into the second testcase, and that passing seems to actually be its intended purpose.  The run-2-only-if-1-passes is only a side effect, in that 1 had to succeed in order to pass the artifact to 2, and thus only by reaching that artifact pass point would 2 be executed.

Granted, this is speculation on my part, judging from both docs, but is also informed by the behavior I see from Codeception's annotation.

**Comment by DavertMik** [comment]
Dependencies were updated in Codeception 2.2 and now they are far more better as in PHPUNit as you can point dependency to other class and be ensured that the one which depends on other won't be executed before.
