### ISSUE TITLE
Weird Laravel 5 ErrorException - Tests work when module is removed

### ISSUE THREAD

**Issue by olimorris** [Codeception/Codeception#1837]
Just doing a composer update and my Codeception 2.0.@dev has been downgraded to 2.0.9 and with it has come this error:
```
[ErrorException]
  Missing argument 1 for Illuminate\Support\Manager::createDriver(), called in /home/vagrant/Code/Project/vendor/laravel/framework/src/Illuminate/Support/Manager.php on line 89 and defined
```

I have reinstalled the separate Laravel5 module however that still didn't work. When I strip out the Laravel5 module though my unit tests work perfectly.

**Comment by janhenkgerritsen** [comment]
You should remove the `janhenkgerritsen/codeception-laravel5` package if you still have that listed in your `composer.json` file. This module comes with Codeception since version 2.0.11.

The reason of the downgrade is that I recently changed the requirements of the `janhenkgerritsen/codeception-laravel5` package, it now requires a version of Codeception <2.0.11, because otherwise users will have two versions of the Laravel 5 module installed which made debugging problems a lot harder, since most users were not aware of this fact.
