### ISSUE TITLE
Phalcon 2.0 broke the Click method

### ISSUE THREAD

**Issue by andreroggeri** [Codeception/Codeception#1863]
```
private function login($I, $u = "admin@piv.com.br", $p = "admin"){
        $I->amOnPage('admin/login');
        $I->fillField('email', $u);
        $I->fillField('senha', $p);
        $I->click('Entrar');
        $I->see('Administrador');
    }
```
The code above work as expected on Phalcon1, but after upgrading to Phalcon2 it fails on Click step. And this should happen because Phalcon2 API is the same as Phalcon1.

Stacktrace in here: http://pastebin.com/H2VpXN8c

I wonder where to start to search the bug ?

**Comment by DavertMik** [comment]
Phalcon2 is not yet supported. Please wait for Phalcon2 module

**Comment by andreroggeri** [comment]
I understand that.

Phalcon2 API is the same(should be) as Phalcon1, so this module should work.
Other methods like see, amOnPage works fine.
Can you give me directions where I should look to fix the Click method on codeception source ?

I really appreciate your support.

**Comment by DavertMik** [comment]
Looks like there is something with session. In test mode `session_start` should never be called (at least twice). 

Take a look here: https://github.com/Codeception/Codeception/blob/2.0/src%2FCodeception%2FLib%2FConnector%2FPhalcon1.php#L48

Here we create a request that will be passed into the Phalcon framework. `amOnPage` in your case passed correctly because it was *first* request, and the second one cause this session error. So you should do smth so Phalcon didn't recreate sessions in testing mode. Maybe you will need to connect framework developers.

**Comment by DavertMik** [comment]
I'd ask @niden to join this discussion and maybe provide some ideas to solve this issue )

**Comment by andreroggeri** [comment]
@DavertMik the issue seems to be on my configuration.

I have a multi module application, and the session service was registered three times.


Later i'll confirm that works as expected and close this issue.


Thank you very much for you support !!

**Comment by andreroggeri** [comment]
So far so good ! :)

Phalcon1 module seems to be compatible with Phalcon2

Thanks for you support @DavertMik
