### ISSUE TITLE
PhpBrowser see/dontSee with HTML

### ISSUE THREAD

**Issue by alexwhitman** [Codeception/Codeception#1873]
In porting some tests from 1.8 to 2.0 I've found an odd issue with `see` and `dontSee` when there are HTML elements within the string being tested.  For example, take the following HTML
```html
<p>This is a sentence containing a <b>bold</b> word.</p>
```
which is rendered as
This is a sentence containing a __bold__ word.

In 1.8 I could use
```php
$I->see('This is a sentence containing a bold word');
```
and the test would pass.  The same assertion in 2.0 fails.  In 2.0 I have to either include the HTML:
```php
$I->see('This is a sentence containing a <b>bold</b> word');
```
or pass in a selector as the second parameter:
```php
$I->see('This is a sentence containing a bold word', 'body');
```
This seems to be because of way the text is checked depending on whether a selector is used or not in https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Lib/InnerBrowser.php#L140

**Comment by zbateson** [comment]
@alexwhitman - I too have noticed this.  My preference would be for it to work as it did in 1.8.  @DavertMik - the documentation doesn't say anything specific about this behaviour (that I can find).  Could you clarify if it's intentionally done this way?

**Comment by DavertMik** [comment]
Actually I missed this thing while creating PhpBrowser for Codeception 2.0
I rewrote PhpBrowser with a new engine, removing Mink + Goutte driver, that's why the behavior changed. 

Probably the behavior should be as it was in 1.8 if there are no counterpoints against it. Looks like we need to use strip_tags before making lookup with `see`/`dontSee`
