### ISSUE TITLE
selectOption doesn't seem to select an option

### ISSUE THREAD

**Issue by jrm2k6** [Codeception/Codeception#1901]
Suite type: functional
Codeception version 2.0.13

I have the following html:

```
<html>
<body>
    <form>
        <select name="test1" id="test">
            <option value="1">One</option>
            <option value="2">Two</option>
            <option value="3">Three</option>
        </select>
    </form>
</body>
</html>
```

And the following test:

```
<?php
$I = new FunctionalTester($scenario);

$I->amOnPage('/admin/consultations/view/1');
$option = $I->grabTextFrom('form select[name=test1] option:nth-child(2)');
// This prints 'Two' when calling dd()
$I->selectOption("form select[name=test1]", $option);
//$I->seeOptionIsSelected("#test", 'Two');
$I->seeInField("#test", 'Two');
```

Error received:
```
Couldn't see in field "#test","Two":
Failed asserting that an array contains 'Two'.

Scenario Steps:
4. I see in field "#test","Two"
3. I select option "#test","Two"
2. I grab text from "form select[name=test1] option:nth-child(2)"
1. I am on page "/admin/consultations/view/1"


FAILURES!
Tests: 4, Assertions: 1, Failures: 1.
```

When using seeOptionIsSelected instead of seeInField I got:

```
Couldn't see option is selected "#test","Two":
Element located either by name, CSS or XPath 'selected option' was not found on page.

Scenario Steps:
4. I see option is selected "#test","Two"
3. I select option "#test","Two"
2. I grab text from "form select[name=test1] option:nth-child(2)"
1. I am on page "/admin/consultations/view/1"


FAILURES!
Tests: 4, Assertions: 1, Failures: 1.
```

Now, if I apply a selected value to the html form as:
```
<html>
<body>
    <form>
        <select name="test1" id="test">
            <option value="1" selected="selected">One</option>
            <option value="2">Two</option>
            <option value="3">Three</option>
        </select>
    </form>
</body>
</html>
```

I get 
```
Couldn't see option is selected "#test","Two":
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Two'
+'One'

Scenario Steps:
4. I see option is selected "#test","Two"
3. I select option "#test","Two"
2. I grab text from "form select[name=test1] option:nth-child(2)"
1. I am on page "/admin/consultations/view/1"
```
So I know it is seeing the select element correctly, it doesn't apply the new selection to it.
Clicking on the form before selecting does not change anything.

I started by having the issue with a Laravel form, but wanted to test on a really simple html form first.

Is there anything I am doing wrong?

**Comment by zbateson** [comment]
Hello,

You've hit a documentation issue.  I can't remember why selectOption was needed so I've been delaying the update to docs to see if we can just get rid of it (or replace its code with a call to fillField)

You should be able to use fillField and seeInField instead.

**Comment by montogeek** [comment]
Can you please test with: `form select[name="test1"]` ?

**Comment by jrm2k6** [comment]
Will do asap

**Comment by jrm2k6** [comment]
@zbateson I tried with fillField and seeInField but it is still failing. I can setup a small test project tomorrow. Is the html/scenario also failing for you?

@montogeek I tried with ```form select[name="test1"]``` (as described in my test case) and it doesn't change anything.

**Comment by zbateson** [comment]
Hi @jrm2k6,

Could you repost your code using fillField/seeInField and the failure message you're getting?

**Comment by jrm2k6** [comment]
@zbateson can you reproduce? to make sure it is not only a setup issue but really a codeception issue?
Laravel version 4.2
Suite type: functional
Codeception version 2.0.13

```
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<form>
    <select name="test1" id="test">
        <option value="1">One</option>
        <option value="2">Two</option>
        <option value="3">Three</option>
    </select>
</form>
</body>
</html>
```


Test: 
```
$I->amOnPage('/admin/consultations/view/1');
$I->fillField("form select[name=test1]", 2);
$I->seeInField("form select[name=test1]", 'Two');
```
functional.yml

```
# Codeception Test Suite Configuration

# suite for functional (integration) tests.
# emulate web requests and make application process them.
# Include one of framework modules (Symfony2, Yii2, Laravel4) to use it.

class_name: FunctionalTester
modules:
    enabled: [Filesystem, FunctionalHelper, Laravel4, Db]

```
Error:
```
Couldn't fill field "form select[name=test1]",2:
LogicException: An InputFormField can only be created from an input or button tag (select given).

Scenario Steps:
2. I fill field "form select[name=test1]",2
1. I am on page "/admin/consultations/view/1"


  [LogicException] An InputFormField can only be created from an input or button tag (select given).

#1  /home/vagrant/pocketderm.dev/PocketDerm/vendor/symfony/dom-crawler/Symfony/Component/DomCrawler/Field/FormField.php:57
#2  Codeception\Lib\InnerBrowser->fillField
#3  /home/vagrant/pocketderm.dev/PocketDerm/tests/functional/FunctionalTester.php:1921
#4  /home/vagrant/pocketderm.dev/PocketDerm/tests/functional/SubmitConsultationCept.php:5
#5  Codeception\TestCase\Cept->testCodecept

FAILURES!
Tests: 3, Assertions: 0, Errors: 1.
```

**Comment by zbateson** [comment]
Hi @jrm2k6 

Apologies - it seems I misled you.  I really shouldn't respond when tired!  Your first example was correct... you should use ```selectOption``` the issue is $I->seeInField("#test", 'Two'); is incorrect because the value of the field is actually '2' not 'Two'.  You can, however, use ```selectOption``` with the 'text' of the select.

Your script should be:

```php
//...
$option = $I->grabTextFrom('form select[name=test1] option:nth-child(2)');
// This prints 'Two' when calling dd()
$I->selectOption("form select[name=test1]", $option);
$I->seeInField("#test", '2');
```

Unfortunately I don't have the time to test out every issue, normally the issues that come through aren't actually Codeception issues they're mostly usage issues (and debugging them isn't always fun ;)).  I ended up testing yours though because I didn't notice right away that you were checking for 'Two' versus the option's value of '2' so momentarily wondered if it was a Codeception issue.  Codeception has a bunch of tests built-in.  You can have a look at them in [https://github.com/Codeception/Codeception/blob/2.0/tests/unit/Codeception/Module/TestsForWeb.php].  They still need more work.

At some point I'll clean up the discrepancies between selectOption/fillField/seeOptionIsSelected when I have a moment!

**Comment by jrm2k6** [comment]
Hi @zbateson 
Yes I also tried with specifying the value of the option, but it still doesn't work.
So the issue is that I still don't know if my usage is wrong or something with codeception is wrong. I will create a small fork, totally separate from my laravel app to make sure it works and will get back to you.

Thanks!

**Comment by zbateson** [comment]
@jrm2k6,

Hmm... curious.  Given the example HTML page you posted I can tell you it worked with our FrameworksTest.  As far as I can tell the Laravel module doesn't override anything that would cause it to break.

**Comment by jrm2k6** [comment]
@zbateson Yes I feel there are too many variables right now, so I will create a test example and go from there.

**Comment by zbateson** [comment]
Hi @jrm2k6 - any update on this, were you able to work it out?

**Comment by jrm2k6** [comment]
Hi @zbateson, no update so far. Been busy so no time to play with it. Found a workaround: move to unit tests :)

Will try to setup the different tests soon!

**Comment by zbateson** [comment]
No worries @jrm2k6 :smile: I will close for now - feel free to reopen or create a new issue when you get back to it!

**Comment by zmilan** [comment]
Hi, I just wish to share this for the record :)
I experienced similar issue yesterday. I had this code:
`$option = $I->grabValueFrom(CheckoutPage::$shippingRateSelectSelectorDomestic . ' option:nth-child(2)');`
`$I->selectOption(CheckoutPage::$shippingRateSelectSelectorDomestic, $option);`
`$I->seeInField(CheckoutPage::$shippingRateSelectSelectorDomestic, $option);`
It didn't select option from select box, but didn't also throw any error. So my test fail on next step, since element that should become visible after selecting option from select doesn't become visible.
After a lot of different ideas how to solve this, I come with this one:
`$this->executeJS('
            $(\''.$selector.' option\').removeAttr("selected"); 
            $(\'' . $selector . ' option[value="' . $value . '"]\').attr("selected", true); 
            $(\'' . $selector . '\').change();
        ');`
It works fine now and I think I understand now what was real issue. Our generated select tag has first option like this:
`<option disabled="true" selected="selected">Select shipping service</option>` 
And issue is with this selected="selected". If you look at first line in my solution I was forced to remove "selected" attribute from all options before I select new one. Without that line any solution wasn't work.

**Comment by BharathkumarDS** [comment]
I am still getting this issue, Wherever the Select dropdown is having  <option disabled="true" selected="selected"> as the first option, I .selectoption is not working and Codecept is not identifying the element or clicking the element as well. Did anyone fid any solution for this?
