### ISSUE TITLE
Codeception conceals helper class loading errors

### ISSUE THREAD

**Issue by codedokode** [Codeception/Codeception#1913]
Steps to reproduce: 

1. wget latest phar: `wget http://codeception.com/codecept.phar`
2. bootstrap a new project: `php codecept.phar bootstrap`
3. modify `tests/_support/AcceptanceHelper.php` to make it unloadable, e.g.
```php
<?php
namespace Codeception\Module;

class AcceptanceHelper extends \Codeception\InexistingModule
{

}
```
Now run tests: `php codecept.phar run`

Expected result: error message

Actual result: codeception exits with code 255 after printing 2 lines:

```
Codeception PHP Testing Framework v2.0.13
Powered by PHPUnit 4.6.6 by Sebastian Bergmann and contributors.
```

If we remove `@` signs in these lines: 

https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Configuration.php#L319
https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Configuration.php#L322

the exception message is printed to output:

`PHP Fatal error:  Class '...' not found in ... on line 10`

These silencing operators seem to be part of some fix for Yii: https://github.com/Codeception/Codeception/commit/12179ed802427d6c389da023a6a5c8364c284298

Maybe the fix could be done some other way or used only when Yii module is enabled?

**Comment by codedokode** [comment]
I also tried command-line switches like `--debug`, `-vvv`, `--fail-fast` and none of them shows error message.

**Comment by dave-newson** [comment]
Nothing to do with error suppression, but on `2.1` I'm seeing this "suppression" simply because on the CLI there's no error reporting enabled, even with `-vvv`.

Because of this, a simple parse error wasn't getting displayed, and we got no output from codecept.

We sorta-kinda fixed this by throwing the usual error reporting lines into `_bootstrap.php`:
```php
error_reporting(E_ALL);
ini_set('display_errors', true);
```
Perhaps this can be tweaked in Codecept to ensure all error reporting is switch on by the use of -vvv (debug level)?

**Comment by codedokode** [comment]
Rested with current codeception version (2.1.7) - the error now is reported correctly: 

> Codeception PHP Testing Framework v2.1.7
> Powered by PHPUnit 4.8.23 by Sebastian Bergmann and contributors.
> PHP Fatal error:  Class 'Codeception\InexistingModule' not found in D:\tmp\codecept\tests\
_support\Helper\Acceptance.php on line 8

So the bug is fixed now and I will close it.

> I'm seeing this "suppression" simply because on the CLI there's no error reporting enabled, even with -vvv.
I have checked - on my linux installation (debian) for reasons unknown error reporting is disabled in config by default: 

> cat /etc/php5/cli/php.ini | grep -v '^;' | grep display_error
> display_errors = Off
Which is pretty weird choice. I think it is not codeception devs who should fix this.

**Comment by dave-newson** [comment]
I'm happy with the close, good job taking the time to recheck :)

I think forcing the debugging messages on, when `-vvv` or perhaps a `--debug` arg are given would be beneficial; both you and I expected it to be on by default for CLI, but it is not, leading to spurious reports and time wasted debugging.

It's made worse because the `symfony/console` seems to successfully capture and report exceptions regardless of the setting, but the standard PHP errors (at least until we get PHP7) slip through unreported.

I'm not inclined to chase this one though. As you said - totally up to the author.

**Comment by codedokode** [comment]
By the way you can turn errors into exceptions with [ErrorException](http://php.net/manual/en/class.errorexception.php) class.
