### ISSUE TITLE
Problem in the "see" method

### ISSUE THREAD

**Issue by RayRom** [Codeception/Codeception#1946]
To version 2.0.13 worked normally, after updating the test working before started vydvat a mistake:
$I->see('серебро' , '#objects');
```
Failed asserting that any element by '#objects' on page &lt;bold&gt;/search.php?vr=0&amp;searchtype=1&amp;search=%F1%E5%F0%E5%E1%F0%EE&lt;/bold&gt;
Elements: 
+ &lt;info&gt;&lt;form&gt; Серьги "Серебро на черном"
Белкина Инга
2 300 руб
В корзину
Серьги "Серебро с перидотом"
Белкина Инга
4 200 руб
В корзину
Серьги "Агат в серебре"
Белкина Инга
1 400 руб
В корзину
Колье "Серебро и жемчуг"
Белкина Инга
3 900 руб
В корзину
.............
Для примера&lt;/info&gt;
contains text 'серебро'

/mnt/trunc/tests/acceptance/AcceptanceTester.php:318
/mnt/trunc/tests/acceptance/00_NotInFilesetCept.php:16
```
Though the word "серебро" meets twice

**Comment by zbateson** [comment]
Hi RayRom - which module are you using?  Is this PhpBrowser/Selenium/some framework?  Also it's not complaining about 'серебро' it's complaining about not finding an element matching '#objects'.  Is there an element with that ID on the page?

**Comment by zbateson** [comment]
Oh, I see the issue - sorry misread that yesterday.

'серебро' != 'Серебро'

should be

``` $I->see('Cеребро' , '#objects'); ``` please update and close if that's the issue or let me know if it's something else :smile:

**Comment by RayRom** [comment]
Then why worked to version 2.0.13? Tried and from a capital letter, the mistake remains.
I use webdriver (selenium).

PS: eregi() ?

**Comment by zbateson** [comment]
Testing locally (admittedly on 2.0.14) and everything works fine with WebDriver/selenium for me.  I noticed copy/pasting my $I->see('Cеребро' , '#objects'); line above did not work however, and I think there's a character difference in my "C" character versus the Cyrillic character for "C".  Not sure if that's the issue, but when I copied your 'Серебро' used in your $I->assertContains (or if I copied it directly from the test page I created, or your initial error) it worked fine.

Otherwise, I'm not sure what else may be causing the issue.

**Comment by dynasource** [comment]
@DavertMik: can you tell us if something has changed since 2.0.13 with respect to the see method? Are there changes in Symfony or Guzzle which make tests fail when looking for texts inside HTML code like in scripts or attributes, or so called no visible text
