### ISSUE TITLE
Laravel testing traits integration

### ISSUE THREAD

**Issue by younes0** [Codeception/Codeception#2095]
There are many useful Laravel testing traits such as: `withoutMiddleware`, `withoutEvents` etc, see: http://laravel.com/docs/5.1/testing#mocking-events
All these traits are located in `Illuminate\Foundation\Testing`

How could we integrate these in the laravel codeception module ?
For instance, this is a dirty workaround I made to I use one of these:

```php
public function testStuff() 
{
    $company = factory(Models\Company::class)->create();
    $this->withoutEvents();
}

protected function withoutEvents() // pasted from ApplicationTrait.php
{
    $mock = Mockery::mock('Illuminate\Contracts\Events\Dispatcher');

    $mock->shouldReceive('fire');
    $mock->shouldReceive('listen');

    $this->codeGuy->getApplication()->instance('events', $mock);

    return $this;
}
```

**Comment by janhenkgerritsen** [comment]
These testing traits can only be used with the Laravel test classes, not with the Codeception classes. So your approach of implementing the functionality of the traits yourself is correct.

Of course the functionality of these traits can be mimicked by adding similar functionality to the Laravel5 module, so that it will be possible to do something like

```
$I->haveMiddelwareDisabled();
$I->haveEventsDisabled();
```

I will label this issue as an enhancement, maybe I will implement this sometime in the future. Or someone else can send a pull request.

**Comment by janhenkgerritsen** [comment]
I added `disableMiddleware` and `enableMiddleware` methods to the Laravel5 module in 040c8567bbc6c089727c502008a72317654b92f5. Will take a look at the events functionality another time.

**Comment by janhenkgerritsen** [comment]
I just added the following methods to the Laravel 5 module in aa453d3c84e:

- `disableEvents()`
- `enableEvents()`
- `expectEvents()`

**Comment by younes0** [comment]
thanks!
