### ISSUE TITLE
Provide a way to access Symfony's DI Container

### ISSUE THREAD

**Issue by v3106** [Codeception/Codeception#2188]
http://symfony.com/doc/current/book/testing.html#accessing-the-container
Will this be acceptable?
```diff
diff --git a/src/Codeception/Lib/Connector/Symfony2.php b/src/Codeception/Lib/Connector/Symfony2.php
index 4e7a02c..ffed9d1 100644
--- a/src/Codeception/Lib/Connector/Symfony2.php
+++ b/src/Codeception/Lib/Connector/Symfony2.php
@@ -6,6 +6,11 @@ class Symfony2 extends \Symfony\Component\HttpKernel\Client
     private static $hasPerformedRequest;

     public $persistentServices = [];
+
+    public function getContainer()
+    {
+        return $this->kernel->getContainer();
+    }

     protected function doRequest($request)
     {

```

**Comment by DavertMik** [comment]
There is already `getService` method in Symfony2 module. Check it out

**Comment by v3106** [comment]
I can't find any `getService` method in the sources. If you mean `grabServiceFromContainer`, this is not what I propose. `grabServiceFromContainer` gets services from another kernel, booted in the module, while aforecited method will provide access to services of the app's kernel.

**Comment by DavertMik** [comment]
Ok, I'm not sure but what is the usecase?

**Comment by v3106** [comment]
In my particular case -- sharing the database connection

**Comment by raistlin** [comment]
Method ```grabServiceFromContainer``` returns the service from the booted kernel, so it should return your db service. 
If it's not what you need: could you provide a detailed example of use?

**Comment by raistlin** [comment]
Ping @v3106

**Comment by raistlin** [comment]
Closed because no reporter don't provide additional information.

Reopen as needed.

**Comment by iquito** [comment]
I stumbled upon this issue because I am trying to access Symfony parameter values in Codeception tests ($container->getParameter), and it seems only services can be access with Codeception. My use case are dynamic routes, where part of the routes are defined in application parameters - so to know what URL to call in functional tests, I first need to find out some parameters from Symfony containers.

Is there a way of doing this / can parameters be made available with Codeception?

**Comment by raistlin** [comment]
@iquito see #3251

**Comment by iquito** [comment]
I just commented in this issue - my use case is not doable with unit tests and needs parameter values. I think this is a valid use case.

**Comment by oleja** [comment]
I'm having the same issue - in my functional test I want to set up the state of some service before sending a request using the `\Codeception\Module\REST::sendGET` method.
But since symfony app kernel, created in response to the request, and codeception's symfony module use different containers, it's impossible to accomplish.
To me this behaviour seems inconsistent with how it's possible to manipulate the state using `haveInRepository` method.
Am I doing something conceptually wrong? Is it possible to work around and somehow use shared services in both kernels?

**Comment by Naktibalda** [comment]
Use persistService method of Symfony module.

**Comment by oleja** [comment]
@Naktibalda I tried to use it in my test with no success. To get it working I had to dig deeper:
My case is a little bit more complex - my service is listening to doctrine lifecycle events.
This turned out to be an issue, because I also use Doctrine2 module and it's wired with the Symfony module via `depends` config option. The Doctrine2 module calls the `retrieveEntityManager` method on `_beforeSuite`, which forces instantiation of all dependencies of `EntityManager`. `EntityManager` depends on `\Doctrine\DBAL\Connection`, which, as I see in the dumped container, is configured with a `ContainerAwareEventManager` that routes doctrine events to all the listeners. I.e. calling `retrieveEntityManager` before persisting such a listening service prevents sharing this service, because entity manager is already built with non-shared service at the moment of persisting.
I'm not sure I'm 100% correct, but my current workaround kind of confirms this -- when I persist such services in the `_beforeSuite` method of a custom module, they are shared.
Am I correct about it? Is there a better solution?
