### ISSUE TITLE
Db::select does not quote column

### ISSUE THREAD

**Issue by hmp5bs** [Codeception/Codeception#2199]
Codeception Version 2.1.1

Codeception\Lib\Driver\Db::select does not quote column.
Plus, backquotes is used for table name quoting. (only for MySQL?)

<code>
$query  = "select %s from \`%s\` $where";
</code>
https://github.com/Codeception/Codeception/blob/2.1.1/src/Codeception/Lib/Driver/Db.php#L153

getQuotedName() should be used ?

related:
https://github.com/Codeception/Codeception/issues/1908

**Comment by Naktibalda** [comment]
Using getQuotedName() would break [Module\Db::countInDatabase()](https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Module/Db.php#L353) and has potential of breaking tests for other users.

I wouldn't worry about backquotes in Driver\Db:select(), because majority of drivers override it.

**Comment by DavertMik** [comment]
So what should we do here? // @Naktibalda

**Comment by Naktibalda** [comment]
Close the ticket.

If a user wants to select a column which requires quotes, he can simply add quotes.
Like this $db->select('`order`', 'table')
or even $db->select($db->getQuotedName('order'), 'table') .
