### ISSUE TITLE
Laravel5 module, $I->haveRecordWithNoId() 

### ISSUE THREAD

**Issue by erdemkeren** [Codeception/Codeception#2217]
Laravel 5 module checks for id after inserting a new row into database. However, an id field is not required to have a record in the database.

    public function haveRecord($tableName, $attributes = [])
    {
        $id = $this->app['db']->table($tableName)->insertGetId($attributes);
        if (!$id) {
            $this->fail("Couldn't insert record into table $tableName");
        }

        return $id;
    }

I think it does sth it is not supposed to.

**Comment by janhenkgerritsen** [comment]
The `insertGetId` method of the `Illuminate\Database\Query\Builder` class simply returns the result of a call to `PDO::lastInsertId`, it only converts numeric results to integers. This will be the value of the primary key of the database table, which does not necessarily has to be an id field. In Eloquent you can override this with the `$primaryKey` property in you models.

If you can provide a use case where this method does not work correctly or as you would expect I will consider to remove the check, but for now I don't see any reason to do this.

**Comment by erdemkeren** [comment]
Yes I know that you can override the primary key of eloquent models. And I understand that a model has kinda behaviour. 

But as you can guess, in real life every table that I can have record in it does not have a primary key. And we don't create an eloquent model for every table too. (e.g. relation tables)

I am trying to create a given scene where I have two related records (models) with an additional relation table (belongs to many).

Because I am trying to create dummy data, I don't necessarily grab my services and use them. (To tell the truth, I never use my original codes to create 'given' parts of my tests).

But when I use,

                $this->haveRecord($ctable = "atable_btable", [
                    "a_id" => $aId,
                    "b_id" => $bId
                ]);

I get `Couldn't insert record into table atable_btable.`

And that problem made me write this issue.

**Comment by janhenkgerritsen** [comment]
I agree with your use-case. I probably will remove the check, but first I will look into other ways of determining if an insert succeeded or failed. Otherwise the burden of checking for this will be moved to the caller, which is not something that should happen.

I don't know when I have time to do this, but I will let you know when it's done.

**Comment by erdemkeren** [comment]
Thanks for your concern.

**Comment by janhenkgerritsen** [comment]
It turns out that if there is an error during the call to `insertGetId` an exception is thrown, so I rewrote the method to call the `$this->fail` method only if there is an exception. This should fix your problem.

You can use the 2.0.x-dev or 2.1.x-dev branches to pull in these changes directly or you can wait for the 2.0.17/2.1.2 releases.
