### ISSUE TITLE
Documentation 404

### ISSUE THREAD

**Issue by sharpless512** [Codeception/Codeception#2389]
http://codeception.com/docs/modules/Db

At the text 'Public Properties'
driver - contains Connection Driver. See list all available drivers

The link to 'See list all available drivers' is giving a 404

**Comment by Naktibalda** [comment]
Thanks for report.

Correct link is https://github.com/Codeception/Codeception/tree/2.1/src/Codeception/Lib/Driver
But I think that it should be removed from documentation, because some files in that directory are not database drivers and correct lists of supported databases are given at the top of module documentation and in Status.
