### ISSUE TITLE
Steps output from Module

### ISSUE THREAD

**Issue by codemedic** [Codeception/Codeception#2449]
Is it possible at all to affect the "steps" output from a module.

I am looking at a specific use case where I have a function that wraps a lambda in to a database transaction. https://github.com/natterbox/Codeception-MultiDb/blob/master/examples/tests/acceptance/DemoCest.php

What I want to do is to fence the steps from within the transaction using indents or at least a line with outcome ( commit or rollback ).

**Comment by Naktibalda** [comment]
It seems that what you wanted was very similar to substeps, that were implemented few months before this issue was raised:
![Substeps screenshop](https://codeception.com/images/substeps.png).

> Whenever you have steps grouped inside actor class, pageobject, or stepobject, you can the step executed with its substeps in console or HTML report. 

The problem with your attempt was that you used anonymous function in the test class.
Substep implementation [explicitly ignores code](https://github.com/Codeception/Codeception/blob/4.1.14/src/Codeception/Step.php#L291) from test classes because it would print all test methods as metasteps otherwise.

> * We are using stack trace to analyze if steps were called from test, if not - they were called from meta-step.
