### ISSUE TITLE
amHttpAuthenticated do not add header in debug when testing API

### ISSUE THREAD

**Issue by javigomez** [Codeception/Codeception#2463]
I'm doing this request:

```
		$I->wantTo("check the availability of the webservice");
		$I->amHttpAuthenticated('admin', 'admin');
		$I->sendGET('index.php'
			. '?option=redshopb&view=user'
			. '&api=Hal'
			. '&webserviceClient=site'
			. '&webserviceVersion=1.0.0'
		);
```

I'm using this to launch the tests: `vendor/bin/codecept run --steps --debug tests/api/site.redshopb-user.1.0.0.Cest.php``

The resulting request should have the authorisation header:

![screen shot 2015-10-20 at 11 45 45](https://cloud.githubusercontent.com/assets/1375475/10603868/ee8803ca-7720-11e5-9bba-720e20153152.png)

However notice that the Headers in the debug appears empty, not showing the authentication header:

![screen shot 2015-10-20 at 11 52 20](https://cloud.githubusercontent.com/assets/1375475/10603887/0ed7e474-7721-11e5-923d-1fb9c66d995b.png)

If I do this instead:

![screen shot 2015-10-20 at 12 01 55](https://cloud.githubusercontent.com/assets/1375475/10604082/60acf6b2-7722-11e5-89c6-b69a983c193d.png)

I get the header:

![screen shot 2015-10-20 at 12 02 15](https://cloud.githubusercontent.com/assets/1375475/10604088/6ecab702-7722-11e5-99fe-8bbbe91fa38d.png)

I don't know if this was done in purpose, but I think that: `$I->amHttpAuthenticated('admin', 'admin');`  should add the Header to the following requests. Isn't it?

**Comment by Naktibalda** [comment]
It is the output issue only, authentication should be working.

amHttpAuthentications sets request option 'auth' for Guzzle Client,
https://github.com/Codeception/Codeception/blob/6f30eeb1032cff54ffcf99a87b01d8d6c839450b/src/Codeception/Module/REST.php#L251

The only way to make authentication header appear in `Request headers` output is to generate authentication token in Codeception code and set it with `haveHttpHeader()` instead of using `$this->client->setAuth()`.

**Comment by javigomez** [comment]
Yes, is only an output issue. It authenticates without issues.
