### ISSUE TITLE
REST module is doing too much

### ISSUE THREAD

**Issue by codemedic** [Codeception/Codeception#2560]
IMO, the REST module could be refactored into three things, or more.

Would it not make sense to create a basic REST module that would talk pure HTTP, then either a layer above it or an encoder that the REST module is composed of can provide semantics for JSON, and XML.

IMO, such an approach will drastically improve the maintainability of this module, and will be a joy to add features in the future.

Here I am specifically referring to functions like `REST::encodeApplicationJson`, which to me are shouting "need refactoring".

PS: As  of `v2.1` there is the new facility called `part`, which in my view, the same effect can be achieved by following pure PHP class inheritance and  / or composition. It is indeed magical to use such annotations to do the job, but at the same time it would increase framework footprint; i.e more maintainability headaches.

**Comment by DavertMik** [comment]
Yes, I can agree with you in some points, that's why the parts conception came in. However, the thing you are not taking into account is usability - the module should be easy in use and configuration. It would be hard to explain why user need to join 3 modules together: REST, JSON, PhpBrowser just to make everything work. Especially if JSON module doesn't work with anything else than REST

**Comment by codemedic** [comment]
I guess what should / could be done is to work on a PoC, equivalent to REST, and see for myself what can be done about it.
