### ISSUE TITLE
Doctrine2 clear UoW between chained tests.

### ISSUE THREAD

**Issue by shulcsm** [Codeception/Codeception#2768]
``` php
    public function testA(\FunctionalTester $I)
    {
       $enityA->add(new EntityB()); 
    }

    /**
     * @before testCreateNew
     */
    public function testB(\FunctionalTester $I)
    {
        $em->flush($entityA);
    }
```

UoW state gets shared between chained steps. If $enityA is has cascade on persists $entityB gets flushed in testB. I'm expecting clean unitOfWork for each step.

**Comment by tiger-seo** [comment]
Well, this behaviour is expected, because it's designed this way. UoW's state is not shared between tests. Please, see `\Codeception\Module\Doctrine2::_after`. This mean that entity manager (and UoW) being cleared after each test, so that next test will have a clean environment and you avoid unexpected collisions and bugs.

**Comment by shulcsm** [comment]
No, i ment ``@before`` http://codeception.com/docs/07-AdvancedUsage#BeforeAfter-Annotations
Example describes exactly my use case (multiple separate requests). Even if it's "by desing", imo module documentation should mention this somewhere explicitly and provide a api for manual clean.

**Comment by tiger-seo** [comment]
@shulcsm , please, provide complete test, which we can use to reproduce the issue
