### ISSUE TITLE
[L5] The disable_event options doesn't disable model events

### ISSUE THREAD

**Issue by Anahkiasen** [Codeception/Codeception#2897]
The Laravel5 module has a `disable_events` which does this:

```php
$this->app->instance('events', $mock);
```

However that doesn't disable model events, as those are fired through the dispatcher that is statically set on the `Illuminate\Database\Eloquent\Model` class. The following works:

```php
$this->app->instance('events', $mock);
Model::setEventDispatcher($mock);
```

**Comment by janhenkgerritsen** [comment]
I will look into this next week, thanks for reporting!

**Comment by janhenkgerritsen** [comment]
The code you provide will indeed ensure that model events are disabled when the `disable_events` configuration option is set to true. However, I am not sure if that is the right thing to do.

My thinking is that you use normal events for things like sending email notifications after registering a new user, but that you use model events for things like data validation and updating related models. In my opinion model events are conceptually at a lower level. So that's why I am not so sure that `disable_events` should also disable model events.

A solution would be to also add an option `disable_model_events`, that way users have more control over which events are disabled.

What are your thoughts on this?

**Comment by Anahkiasen** [comment]
I'm ok with that, what would be its default though? Would it be the value of `disable_events` or just `false`?

**Comment by janhenkgerritsen** [comment]
I am leaning to just `false`, that way you have to explicitly disable the model events. Of course the documentation of the `disable_events` configuration option should make clear that it does not disable model events and that you need to use the `disable_model_events` option for that.

**Comment by Anahkiasen** [comment]
Ok! Sounds good to me

**Comment by Anahkiasen** [comment]
@janhenkgerritsen I just tested in 2.2 and it seems `disable_events` _does_ disable model events even though the documentation states the opposite.

I tested with something basic:

```php
class User extends AbstractModel
{
    protected static function boot()
    {
        static::saving(function() {
           dump('SAVING');
        });
    }
}
```

If I call `User::create()` in one of my tests, nothing happens. But if I set `disable_events` to `false` then I do see `SAVING`
