### ISSUE TITLE
Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms.

### ISSUE THREAD

**Issue by vaidy1234** [Codeception/Codeception#2905]
![untitled](https://cloud.githubusercontent.com/assets/14035808/13766277/633af700-eac5-11e5-8a95-f410142a032c.png)

![untitled2](https://cloud.githubusercontent.com/assets/14035808/13766321/c1a04e8a-eac5-11e5-8256-0a25aaa61f66.png)
Issue:

Upon updating to newer version of Firefox i have outputted the following screen. I had tried to revert back to the previous version as well but the output remains the same. Please suggest ways to get this resolved.
-Vaidy

**Comment by DavertMik** [comment]
Please update the Selenium Server as well. The latest version is 2.52.0

**Comment by vaidy1234** [comment]
Hi @DavertMik please find selenium server details.

![untitled3](https://cloud.githubusercontent.com/assets/14035808/13796723/2be21cc2-eb6d-11e5-9aff-11a0a1279144.png)

**Comment by DavertMik** [comment]
no ideas then. This issue is not directly related to Codeception and as you may find out there are pretty more error reports on StackOverflow with the same description. You can search among them. https://www.google.com.ua/search?q=Unable+to+connect+to+host+127.0.0.1+on+port+7055&gws_rd=cr&ei=HTPpVtL1Hqid6ASekp6YDA

**Comment by javigomez** [comment]
@vaidy1234 make sure you have Firefox 44.0.2 or higuer
