### ISSUE TITLE
Heads up: php-code-coverage breaking change

### ISSUE THREAD

**Issue by mindplay-dk** [Codeception/Codeception#2979]
I'm sure you've seen, `php-code-coverage` 4 will use namespaces, which is a BC break.

You need to update [the version constraint](https://github.com/Codeception/Codeception/blob/2.1/composer.json#L22) in your `composer.json` to exclude the coming 4.x release, or the build will break.

I don't think you can reasonably support both? So at that point, you will probably need to make a major release of the codeception package as well, since there will be no BC due to this change.

**Comment by Naktibalda** [comment]
Thanks for this report.

We don't need to set the upper boundary in composer.json,
PHPUnit is setting it https://github.com/sebastianbergmann/phpunit/blob/5.3/composer.json#L26 `"phpunit/php-code-coverage": "^3.3.0",`

I only added `"phpunit/php-code-coverage": ">=2.1.3",` constraint to our composer.json, because some tests were failing with php-code-coverage 2.1.0 in lowest-dependencies travis build.

Codeception is not using php-code-coverage directly.

**Comment by mindplay-dk** [comment]
Ah, I see now - thanks :-)
