### ISSUE TITLE
Wait for element before action

### ISSUE THREAD

**Issue by henrikauppinen** [Codeception/Codeception#3102]
There's a very typical pattern in acceptance tests:
1. do interaction
2. wait until page loads properly
3. assert or do next interaction

Expecially when testing sites with javascript.

``` php
...
$I->click("#open_animated_dialog");
// javascript does it's thing fetching data and animating stuff
$I->waitForText("Dialog title", $maxTimeout); // must wait, otherwise $I->see fails
$I->see("Dialog title");
$I->click("Close dialog");
...
```

This way the test is stable and runs as fast as possible since no implicit waits have been used.

In most recent projects I've gone and added few wrapper methods to make acceptance tests more clean:

``` php
# AcceptanceTester.php
...
public function wsee($text, $selector = null) {
    $this->waitForText($text, $this->maxTimeout, $selector);
    $this->see($text, $selector);
}
...
```

In some cases this removes almost half of the lines in acceptance tests but most importantly improves the workflow significantly.

I experimented tweaking the [WebDriver module](https://github.com/Codeception/Codeception/blob/master/src/Codeception/Module/WebDriver.php#L634) and this works nicely:

``` php
public function see($text, $selector = null)
    {
        if($this->config['wait_for_elements']) {
            $this->waitForText($text, $this->config['wait_s'], $selector);
        }

        if (!$selector) {
            return $this->assertPageContains($text);
        }
        $nodes = $this->matchVisible($selector);
        $this->assertNodesContain($text, $nodes, $selector);
    }

```

I think this kind of feature would be very nice addition as an option. Any advice or thoughts on this? I'm willing to take this further if this makes any sense.

**Comment by DavertMik** [comment]
Looks really good. I like your approach. Personally never liked all those waits placed everywhere, however I must admit that adding `wait*` into all `see|click` methods may affect the performance.

In [AngularJS module](https://github.com/Codeception/Codeception/blob/master/src/Codeception/Module/AngularJS.php#L111) we wait for page to be completely loaded after each action step to be finished.

This way we can execute a waiter command one time, and then do as many assertions as we need without additional waiter. However, I'm not sure this will work for other web applications.

---

But back to your approach. What if `text/element` already exists on a page. Do we still need run waiter for it? Maybe it can be improved to follow the next schema?

* Check element exists on page
* If not - run `waitForElement`
* do assertion/action

**Comment by henrikauppinen** [comment]
I examined the Angular module and I like module approach as it helps confining functionality from WebDriver. Initially I got worried that it would end up repeating code in two places (original and alternate "patient" version of see/click/etc) and instead modified methods in WebDriver.

After few iterations I came up with this:

```php
# Codeception/Module/WebDriver.php:
public function see($text, $selector = null, $timeout = null)
{
    if($timeout) {
        try {
            $this->see($text, $selector);
        } catch(\PHPUnit_Framework_ExpectationFailedException $e) {
            $this->waitForText($text, $timeout, $selector);
            $this->see($text, $selector);
        }
    }
    else {
        # contents of else is original see() functionality
        if (!$selector) {
            return $this->assertPageContains($text);
        }
        $nodes = $this->matchVisible($selector);
        $this->assertNodesContain($text, $nodes, $selector);
    }
}
```
I created few new tests to Web suite and this works nicely, but it *does* add new parameters and I'm not sure if that's good or bad. Same concept should work with click().
This could be put into a module without repeating code by overriding methods and calling parent::see() instead of $this->see(), so that's a possibility as well.

Anyway, some feedback would be great so I know which way I should take this next.

**Comment by sustmi** [comment]
I too run into the issue that @henrikauppinen describes.

Consider the following example:
```php
$I->click("Submit");
$I->see("Everything was OK");
```

We have JavaScript validation on the Submit button that first validates the form `onSubmit` and then either passes the submit event on or stops sending the form.
We use ChromeDriver which is pretty fast and sometimes it is so fast that it clicks and before the JavaScript validation is finished and the form is sent it already processes the `see()` assertion (we use implicit wait but it only waits for `<body>` element that is still present on the old page).
I do not want to add few milliseconds waits everywhere to my test cases because there can be some JavaScript events on any click.

@DavertMik: I do not think that the proposed @henrikauppinen 's solution will hurt the performance noticeably. The wait will apply only if:
1. The page itself is slow (this is expected behavior)
2. The application has an error and the text will be never found

I think that I think that the second point is not a big issue. If failing test takes let say 5 seconds more it is still OK for me because that does not happen that often.

I will try to use @henrikauppinen 's workaround but I would rather see it as a part of Codeception.

**Comment by henrikauppinen** [comment]
2.3.4 version introduced smart wait feature which resolves this issue.
