### ISSUE TITLE
Suggestion: always have a peer review before merging pull requests to avoid common mistakes/bugs

### ISSUE THREAD

**Issue by stipsan** [Codeception/Codeception#3199]
I've noticed that because of a lot of pull requests getting merged by the author of the commits there's a lot of bugs that could be avoided if a peer did a review of the PR and performed the merge.
I know from my own experience that it's so easy to forget or overlook details that turn out to be important or breaking. And having a peer spend a few minutes looking at your code before merging is usually all it takes, and it's easier for the peer to spot problems in your code since he got a fresh pair of eyes.

I couldn't find an issue about this so forgive me if this have already been discussed 😅

**Comment by DavertMik** [comment]
Yes, we are trying to follow that but the world is not perfect. :+1: for the suggestions. 
The problem is that it can be hard to find reviewer with the experience in that particular part. 
If you are willing to help, we have pending pull requests, to be reviewed. It always takes a day or two (from core team) and about a week (for others) to merge them. 

Just if you are interested in quality you could take a brief look into PRs once in a while. This will help and probably encourage others to help as well.

**Comment by stipsan** [comment]
Ah ok. That makes sense.
Sure, I'd love to help out! 😄 Add me and I'll join in on the pending PRs whenever I got free time 👍

**Comment by Naktibalda** [comment]
You don't need any privileges to perform code reviews, just read the code and make comments.

**Comment by stipsan** [comment]
Yeah sure, I'm subscribed now to this repo anyway so I'll help out whenever 😃

**Comment by Naktibalda** [comment]
@stipsan I see that you gave up.

Would you like to review the upcoming changes in Lumen module?

https://github.com/janhenkgerritsen/Codeception/tree/refactor-lumen-module
