### ISSUE TITLE
Please create new function hoverOverText

### ISSUE THREAD

**Issue by rebajz** [Codeception/Codeception#3240]
For example i will like test: 
$I->amOnUrl('https://www.amazon.com');
$I->hoverOverText('Lists');
$I->see('Find a Gift');
$I->click('Create a List');

I mean, this function will be good for testing drop menus, etc.

**Comment by Naktibalda** [comment]
Try this: `$I->moveMouseOver('//*[contains(text(),"Lists")]');`

**Comment by rebajz** [comment]
:-( not working, in browser isnt opened menu, but in report is this step as OK status

working only (menu is opened):
$I->moveMouseOver('.//*[@id="nav-link-wishlist"]/span[2]');

but i will like write string List, not use xpath...

**Comment by DavertMik** [comment]
or the same but somehow easier to write:

```php
$I->moveMouseOver(Locator::contains('span', 'Lists')); 
```

Anyway it is hard by design to this, as you move mouse only to specific element and not to a text. What should happen if you execute `hoverOverText('a')`. How to guess which letter `a` is expected to be hovered?

Use [Locator](http://codeception.com/docs/reference/Locator) class to create complex XPath locators and all the standard methods, there more than enough of them
