### ISSUE TITLE
Guzzle not found in Codeception 2.1.10

### ISSUE THREAD

**Issue by MAXakaWIZARD** [Codeception/Codeception#3266]
I'm getting this error when running my tests (using PHAR):
```sh
/usr/local/bin/codecept run
```
```
Codeception PHP Testing Framework v2.1.10
Powered by PHPUnit 5.3.5 by Sebastian Bergmann and contributors.
                                                                                    
  [Codeception\Exception\ModuleException]                                                
  PhpBrowser: Guzzle is not installed. Please install `guzzlehttp/guzzle` with composer
```

Codeception `2.1.9` works fine.

**Comment by gdscei** [comment]
What's the composer install output?

**Comment by Naktibalda** [comment]
I can confirm that guzzlehttp/guzzle package is missing in http://codeception.com/releases/2.1.10/codecept.phar
However guzzlehttp/psr7 is included.

The size of that file is 1.1M, the size of [PHP 5,4 build](http://codeception.com/releases/2.1.10/php54/codecept.phar) is 5.0M and it has 2 other issues - If I try to run it with PHP, I get this error:
`PHP Fatal error:  Uncaught exception 'PharException' with message 'manifest cannot be larger than 100 MB in phar`.
PhpBrowser can't browse it too, so I can't check if `guzzlehttp/guzzle` was included, but because of the size, it probably is.

The size of 2.1.9 builds is 3.7M of the main build, and 4.1M of the 5.4 build.

**Comment by MAXakaWIZARD** [comment]
@gdscei I'm using PHAR, guzzle should be bundled inside.

**Comment by MAXakaWIZARD** [comment]
@Naktibalda yes, 5.4 build is also broken, I've reported it here https://github.com/Codeception/Codeception/issues/3265

**Comment by MAXakaWIZARD** [comment]
PhpBrowser's code:
```php
    protected function guessGuzzleConnector()
    {
        if (!class_exists('GuzzleHttp\Client')) {
            throw new ModuleException(
                $this,
                "Guzzle is not installed. Please install `guzzlehttp/guzzle` with composer"
            );
        }
        if (class_exists('GuzzleHttp\Url')) {
            $this->isGuzzlePsr7 = false;
            return new \Codeception\Lib\Connector\Guzzle();
        }
        $this->isGuzzlePsr7 = true;
        return new \Codeception\Lib\Connector\Guzzle6();
    }
```

**Comment by DavertMik** [comment]
Phar was rebult, and tested. PhpBrowser tests are passing

**Comment by Naktibalda** [comment]
The size of  http://codeception.com/releases/2.1.10/codecept.phar is 9.5M,
http://codeception.com/releases/2.1.10/php54/codecept.phar is 9.8M.
Why are they so much larger than 2.1.9?

**Comment by Naktibalda** [comment]
PHP 5.4 build prints `Codeception version 2.2.1`

**Comment by DavertMik** [comment]
Oh :(

**Comment by DavertMik** [comment]
Done
