### ISSUE TITLE
Running with --coverage causes Referer header to not work

### ISSUE THREAD

**Issue by Sazpaimon** [Codeception/Codeception#3268]
If you run a test with `--coverage`, and your test uses `$I->haveHttpHeader('Referer', $ref);`, the referer header doesn't get set correctly, instead it uses the referer header of the application URL being tested. I suspect this is due to how Symfony browser kit internally handles setting this header. I found the following in the `request` method of the browser-kit/Client.php file:

```
if (!$this->history->isEmpty()) {
    $server['HTTP_REFERER'] = $this->history->current()->getUri();
}
```

I think due to the way Codeception calls out to start gathering code coverage, it's adding those requests to the history. Simply not adding to the history when making calls to get code coverage data should fix this.

**Comment by Sazpaimon** [comment]
I was able to make it work by replacing `$this->module->amOnPage('/');` in `startCoverageCollection` in `LocalServer.php` with `$this->module->_request('GET', '/');`. I don't know if that's a solution you'll want though.

**Comment by Naktibalda** [comment]
If it does not disable code coverage collection, it is fine. Please make a pull request.

**Comment by Sazpaimon** [comment]
Unfortunately `_request` is only available in `InnerBrowser` and not part of the public interface, so this wouldn't work if you use the WebDriver for instance. I can't really think of a good solution other than modifying the public interface. Any suggestions?

**Comment by Naktibalda** [comment]
Many things happened since this issue was raised.

Offending line of code [was removed from LocalServer in January 2018](https://github.com/Codeception/Codeception/commit/22c1b9f23503bbd3c9220da6c5b23e3cb9ff1b0f)
And then replaced with loading page [for WebDriver only ](https://github.com/Codeception/Codeception/commit/069f086aea87f64b795060340711190ac74a40a5).

So this issue must be fixed now.
