### ISSUE TITLE
Issue with Laravel5 Module regarding loading of app.php on modular architecture

### ISSUE THREAD

**Issue by goranbosevski** [Codeception/Codeception#3286]
Hi, 
we are using https://github.com/pingpong-labs/modules for ou folder structure, basicaly on teh root we have folder modules and there are our different modules, we want to separate the tests for each module and we bootstrap codeception in each separate module ex. module/some_module, so when I try to enable Laravel5 module in functional.suite.yaml I get error 'Laravel bootstrap file not found' this is because the module is searching the file in the some_module folder.
Any solution to this?

Thank You very much.

**Comment by janhenkgerritsen** [comment]
Have you tried changing the `bootstrap` and `root` configuration parameters of the Laravel 5 module?

For more details see the config section in the [Laravel 5 module documentation](http://codeception.com/docs/modules/Laravel5).

**Comment by goranbosevski** [comment]
Yes I tried, that was first thing I tried. But no matter what is in config, the confid string is added to the project directory in this case the modules/module_folder.

This is the code in which this happens I believe:

$projectDir = explode($this->config['packages'], \Codeception\Configuration::projectDir())[0];
$projectDir .= $this->config['root'];
$this->config['project_dir'] = $projectDir;
$this->config['bootstrap_file'] = $projectDir . $this->config['bootstrap'];

**Comment by janhenkgerritsen** [comment]
And what if you set the `packages` option to `module/some_module`? I am just guessing here though.

Because I am not familiar with the modules package you are using I am not really sure if I understand your problem correctly. I tried to look at the documentation of the package, but the link on the Github page is not working. And I don't have the time to experiment with the package.

Maybe you can setup a small test application that replicates the problem and put it on Github? That way I can take a look at it, that will probably make it easier for me to find a solution.

But if you can find a solution yourself that would be great. If you send a pull request I will be happy to merge it if it doesn't break anything else.

**Comment by goranbosevski** [comment]
I created a demo project https://github.com/goranbosevski/demo-codeception-laravel5module
Run any test from the modules folder using the Laravel5 module, I use the command codecept run -c modules/demo the the error is thrown where it can not locate the Laravel bootstrap file.

Thank You again for helping.

**Comment by janhenkgerritsen** [comment]
You can fix the problem by changing your suite configuration file `modules/Demo/Tests/functional.suite.yml`. You have two options:
- Set the `root` configuration parameter for the Laravel5 module to `"../../"`
- Set the `packages` configuration parameter for the Laravel5 to `"modules/Demo"

After that you can run the command `codecept run functional -c modules/Demo` in the root of your application without the error.

If the changes are not picked up you should check the indentation in your suite configuration file. Make sure you use 4 spaces.

**Comment by goranbosevski** [comment]
It is working, I will close this.
