### ISSUE TITLE
Larave5 module doesn't change environment to .env.testing

### ISSUE THREAD

**Issue by RossTsachev** [Codeception/Codeception#3291]
Hi,
I'm setting Laravel5 module as shown in documentation, however Codeception uses the values from my my original .env file.
Also in the module I don't see where $this->config['environment_file'] is used and can't debug it.

**Comment by janhenkgerritsen** [comment]
Can you show me your suite configuration file? The most common error to get this problem is wrong indentation in the configuration file.

The configured value is used in the connector class, not in the actual module: https://github.com/Codeception/Codeception/blob/2.2/src/Codeception/Lib/Connector/Laravel5.php#L185

**Comment by RossTsachev** [comment]
Figured it out.
I'm using a _bootstrap.php file for my functional tests.
```
$app = require_once './bootstrap/app.php';
require_once './bootstrap/customsitelogic.php';
```
so I added
```
$app->loadEnvironmentFrom('.env.testing');
```
and it detects it now. 
Thanks
