### ISSUE TITLE
if else condition using BDD-codeception

### ISSUE THREAD

**Issue by rajabhaskar** [Codeception/Codeception#3353]
Hi team,
Can any one tell me how to achieve "if-else" condition using BDD(Gherkin) - codeception. I want to do task1 if an element exists on page, else I will perform task2. I hate to write my own custom action for each if else condition as I am working on huge project and if I do so the custom actions will grow like anything. Please advise me the simple way to achieve this. I don't see anything related to this in documentation of BDD-codeception. Can we do this using BDD(Gherkin) ?

**Comment by Naktibalda** [comment]
Conditional test is a bad idea - you should have separate tests for both cases.

**Comment by rajabhaskar** [comment]
But that's my requirement. I don't want at least one test will fail every time I run the test suite. There will be so many cases in real time testing like - if member count>0 ->view members will be the button text else ->'start inviting' will be the button text. I can't write it as two separate scenarios in which at least one  will fail each time... Please provide me if there is any workaround. Thanks

**Comment by Naktibalda** [comment]
Use Db module to setup database.
In the first test don't add any members and check if Start Inviting is visible.
In the second test add some members and check if View Members is visible.

**Comment by DavertMik** [comment]
> I hate to write my own custom action for each if else condition

Looks like you will need to. 
Anyway, conditions in tests is "code smell". You are trying to do something wrong. 
No matter how huge your project is, you should have different scenarios for different cases. Scenarios should be predictable otherwise you won't be sure which actual scenario has passed. Sorry, I can't give you more advice on that.

Just don't include any logic into tests. Use PageObjects to handle similar actions but use different tests to test different scenarios.
