### ISSUE TITLE
Add support for Phive

### ISSUE THREAD

**Issue by SamMousa** [Codeception/Codeception#3419]
#### What are you trying to achieve?

Installing codeception via Phive (https://github.com/phar-io/phive)
#### What do you get instead?

Can't install it.

The advantage of Phive is that it automates signature checking, it could be considered as a composer for phars.

**Comment by Naktibalda** [comment]
Does it support providing different phar files for different version of PHP?
e.g. http://codeception.com/releases/2.2.3/codecept.phar for PHP 5.6+
and http://codeception.com/releases/2.2.3/php54/codecept.phar for PHP 5.4 - 5.5.

Phive claims that one of the benefits is
> Alternatively, you could have used composer. And cluttered your project's dependencies with the ones of your tools. And fight their potential dependency conflicts. 

It is a false claim, especially for Codeception,
I helped to solve many issues caused by dependency conflicts of phar files here and in StackOverflow.

Codeception consumes 7 Symfony components and Guzzle library.
When testing Symfony or Laravel projects it is very important to have matching versions of components or fatal errors will happen and the only way to avoid version mismatch is to use composer.
(composer global install is as bad as phar files)

**Comment by SamMousa** [comment]
@Naktibalda it supports versioning of the phar file, i'm not sure if it supports "binding" them to specific php versions. Although I think that could be worked out by using `--temporary` to install a specific version in a specific test environment.

I agree on your second argument and have run into trouble myself when using codeception from a `phar` file. Honestly I'm not sure what the best approach is, I do know that several other projects explicitly choose not to have their tools in their `composer.json`.

**Comment by Naktibalda** [comment]
Actually, we don't need support for multiple phar files, because Phive only runs on PHP 5.6+
so it could be used to install our main build.

**Comment by SamMousa** [comment]
In that case implementation of support would be simpler but also less complete.
Still, as I mentioned, I'm not sure codeception really works from a phar... I get errors when running it since   my setup requires a codeception plugin; basically the phar only works when you require vanilla codeception I guess?

If running from a phar is a valid option then support for phive would be greatly appreciated!
