### ISSUE TITLE
InnerBrowser Unknown modifier

### ISSUE THREAD

**Issue by nathanphan** [Codeception/Codeception#3581]
#### What are you trying to achieve?
I am using click like this:

`$I->click('Create Hotfix', 'li.active');`

I see this in log

` preg_match(): Unknown modifier '/' in file /var/www/devops/protected/vendor/codeception/codeception/src/Codeception/Lib/InnerBrowser.php at line 202`

My functional.suite.yml is

`modules:
    enabled:
        # add framework module here
        - Yii1:
            appPath: 'public/test.php'
            url: 'http://mysite.local/test.php'
`

When I use var_dump before line 202 in InnerBrowser.php for the $pattern variable, it gives me this

`/^http\\://mysite\\.local$/u`

Which is wrong. It should be 

`/^http:\/\/mysite\.local$/u`

Please help

**Comment by amashigeseiji** [comment]
I think the cause of this problem is `\Codeception\Module\Yii1::getDomainRegex:227`.

`InnerBrowser::isInternalDomain` calls `\Codeception\Module\Yii1::getInternalDomains`.

line 248 of `\Codeception\Module\Yii1`(`getInternalDomain`) is:
```
        $domains = [$this->getDomainRegex(Yii::app()->request->getHostInfo())];
```

and line 227 of `\Codeception\Module\Yii1`(`getDomainRegex`) is:
```
        if (preg_match('#https?://(.*?)/#', $template, $matches)) {
```

`Yii::app()->request->getHostInfo()` returns `http://mysite.local`, not `http://mysite.local/`,
so `preg_match` on line 227 (`\Codeception\Module\Yii1::getDomainRegex)` does not operate as expected.
Regex pattern of `preg_match` on line 227 expects argument with trailing slash like `http://mysite.local/`.

I think [this commit](https://github.com/amashigeseiji/Codeception/commit/ff8804ce487a5e98daa59042ffc6455426aaecb2?diff=unifie://github.com/amashigeseiji/Codeception/commit/ff8804ce487a5e98daa59042ffc6455426aaecb2?diff=unified) will solve your problem.

**Comment by nathanphan** [comment]
I got your point but when it comes to line 202 in InnerBrowser.php 

the $pattern and $domain cannot be matched.

**Comment by amashigeseiji** [comment]
yes, I see.
This is a bug of `Yii1::getInternalDomain` that returns invalid regex pattern.
`getInternalDomain` should return `/^mysite.local$/u`, not `/^https?://mysite.local$/u` or `/^https?:\/\/mysite.local$/u`.

 argument of `InnerBrowser::isInternalDomain` is:
```php
169            if (preg_match('#^(//|https?://(?!localhost))#', $uri)) {
170                $hostname = parse_url($uri, PHP_URL_HOST);
171                if (!$this->isInternalDomain($hostname)) {
```

`$hostname` is like `mysite.local`, so that `/^https?:\/\/mysite.local$/u` does not match `mysite.local` and `InnerBrowser::isInternalDomain` returns false. It is not expected.

**Comment by nathanphan** [comment]
I have pull request here https://github.com/Codeception/Codeception/pull/3582

but my editor is some kind of suck...
