### ISSUE TITLE
GroupObject event (suite.before) is run even though group param is not specified

### ISSUE THREAD

**Issue by mikeuding** [Codeception/Codeception#3703]
#### What are you trying to achieve?
```bash
codecept run api --debug
```

#### What do you get?

```bash
Codeception PHP Testing Framework v2.2.6
Powered by PHPUnit 5.5.6 by Sebastian Bergmann and contributors.

Rebuilding ApiTester...

Api Tests (0) ----

Modules: REST, PhpBrowser, Asserts, \Helper\Api
----
Died here
```

```php
<?php
namespace Group;

class Test extends \Codeception\Platform\Group
{
    public static $group = 'test';

    public static $events = [
        Events::SUITE_BEFORE => 'compile'
    ];
  public function compile() { die('Died here'); }

}
```

### Details

* Codeception version: 2.2.6
* PHP Version: 5.6.22
* Operating System: Ubuntu
* Installation type: Phar
* Suite configuration: codeception.yml
```yaml
extensions:
    enabled:
        - Group\Test
```

**Comment by DavertMik** [comment]
Yep, GroupObject is just an extension, right? So it allows you to do everything that extension can, especially listen to all the events. If a ` public static $group` is set it allows to listen for `before/after` event of a test of this specific group.

There is no way to listen to a group event in `beforeSuite` just because when we start suite we have no idea about groups of tests to be executed.
