### ISSUE TITLE
Innerbrowser submitForm uses wrong value for select.

### ISSUE THREAD

**Issue by JorisVanEijden** [Codeception/Codeception#3824]
### Problem:
`getFormFromCrawler() ` in the InnerBrowser adds an empty option to select elements that have no empty options.

This results in `submitForm()` submitting this empty value in stead of the default.

Testform:
```html
<form method="post">
    <select name="test">
        <option value="_none">- None -</option>
    </select>
</form>
```

There is no option without a value and no default selected option so the `getFormFromCrawler()` method adds one:
```html
    <select name="test">
        <option value=""></option>
        <option value="_none">- None -</option>
    </select>
```

The `submitForm()` method now submits `test=""` in stead of the correct `test="_none"`

### Solution:
1. Find out why extra `<option>` adding code was added in commit c048980e318850c154d789d5ce5d69952a6cef60
2. Create another solution for whatever problem the extra `<option>` fixed.
3. Remove the extra `<option>` adding code.

### Details:
* Codeception version: 2.2.6

**Comment by JorisVanEijden** [comment]
I created a PR: #3825

**Comment by zbateson** [comment]
Hi @JorisVanEijden 

It's been a while since I've been active on this project -- but looking at my comment in the docblock it says "Codeception expects an empty value to match an unselected select box."

It's also possible that scenario isn't tested specifically, or its been fixed, but I expect since my code hadn't yet been removed that it probably hasn't been addressed :)
