### ISSUE TITLE
Feature before and after event

### ISSUE THREAD

**Issue by gimler** [Codeception/Codeception#3842]
#### What are you trying to achieve?
I try to switch from behat to codeception. I need to reset the database after each feature file that has the reet tag. After test is executed after each scenario. And after suite after the hole run.

Possible Workarounds

1. Explicit Step in the first szenario that reset the db
2. Tag the first szenario insteeat the feature

Is there a nother way. I would prefer to do the reset in a extension

**Comment by DavertMik** [comment]
> the reet tag

probably you mean `@reset` tag.
I think the best workaround for you is [GroupObjects](http://codeception.com/docs/08-Customization#Group-Objects). I think they are fit well for your case

**Comment by gimler** [comment]
Yes i mean @reset. How can i use groupobject in gherkin context? What are the difference between extension with events and groupobjects.

**Comment by DavertMik** [comment]
> How can i use groupobject in gherkin context?

Just as for other tests. Any test or feature scenario with `@reset` group will be handled by Group Object.

> What are the difference between extension with events and groupobjects.

Technically, groupobject is an extension. But it listens only for event of specific group.
Unfortunately there is no such event as `beforeFeature` (because tests can be executed in random order) but there are `test.before` and `test.after`, groupobject will handle that events for tests belonging to specific group.`

**Comment by gimler** [comment]
it works.
