### ISSUE TITLE
codecept -c common/ g:pageobject Login produced wrong namespaces (yii2-app-advanced)

### ISSUE THREAD

**Issue by bscheshirwork** [Codeception/Codeception#3924]
#### What are you trying to achieve?

`codecept -c common/ g:pageobject Login`

Can generated real path namespace is
`namespace common\tests\_support\Page;`
or resolve path (I put additional alias)
`Yii::setAlias('common/tests/Page', '@common/tests/_support/Page');`

#### What do you get instead?

short namespace
`namespace common\tests\Page;`

### Details

* Codeception version: Codeception PHP Testing Framework v2.2.7
Powered by PHPUnit 5.7.5-48-g511c9a1 by Sebastian Bergmann and contributors.
* PHP Version: 7.1
* Operating System: debian:jessie
* Installation type: Docker image
* Suite configuration: like yiisoft/yii2-app-advanced

**Comment by DavertMik** [comment]
Yes, current behavior is breaking PSR-4, however it won't be changed in nearest future. 
Probably you don't need to access Page objects or tests from parts other than Codeception, so that should not be a huge problem.

Now you can set only a global prefixed namespace for everything generated inside your test folder. However, namespaces for support classes and tests will be use the same prefix.
