### ISSUE TITLE
_bootstrap.php does not introduce variable for tests

### ISSUE THREAD

**Issue by PunchyRascal** [Codeception/Codeception#3949]
#### What are you trying to achieve?
Have some variables ready in tests, like the bootstrap file suggests:
// Here you can initialize variables that will be available to your tests
#### What do you get instead?
undefined variables

### Details

* Codeception version: 2.1.8
* PHP Version: 7.0.13
* Operating System: Win10
* Installation type: Composer

I am talking about `codeception/acceptance/_bootstrap.php`

**Comment by DavertMik** [comment]
yes, sorry this was working for Cept files in early days of Codeception but since we got other formats, they are not support. This is technical limitation of PHP. I think in next versions _bootstrap will be disabled or deprecated.

It is recommended to have shared variables in Actor class, or inside PageObjects.
