### ISSUE TITLE
Access to Lavarel environment variables

### ISSUE THREAD

**Issue by edno** [Codeception/Codeception#4054]
In some cases, it can be useful to access to some Laravel environment variables.

In one of my project I have implemented an [helper](https://github.com/edno/kleis/blob/develop/tests/_support/Helper/Laravel5Extension.php) supporting this feature:
```php
    public function setEnvironmentVariable($var, $value)
    {
        $this->app['config']->set($var, $value);
    }
    public function grabEnvironmentVariable($var)
    {
        return $this->app['config']->get($var);
    }
    public function seeInEnvironmentVariable($var, $expected)
    {
        $value = $this->grabEnvironmentVariable($var);
        $I = $this->getModule('Asserts');
        $I->assertEquals($expected, $value);
    }
    public function dontSeeInEnvironmentVariable($var, $expected)
    {
        $value = $this->grabEnvironmentVariable($var);
        $I = $this->getModule('Asserts');
        $I->assertNotEquals($expected, $value);
    }
```

If okay with the community then I'll push this into a PR.

**Comment by janhenkgerritsen** [comment]
I don't think this should be in the Laravel module. First of all I don't like the usage of the words environment variable, since you are actually just checking config values. 

Besides that I also think this is a very specific use case, for which you can easily write a helper if you really need it, just like you have done yourself.

Furthermore the Laravel application object is already exposed on the module, so you can already access config values via that object in your tests if you like.

If you do think this should be in the Laravel module please convince me with some use cases.

**Comment by edno** [comment]
Names can be changed to 'configuration value' if it sounds better 😄 

In my case, I've implemented this because my application has specific parameters that are not accessible from the UI. However I want to have the ability to change them without having to rebuild a new instance. But as you said, maybe it only fits to this case, hence no need to be part of Laravel module.

**Comment by janhenkgerritsen** [comment]
Yeah I think it's too specific, so I rather leave it out of the module. But thanks for the suggestion anyway :)
