### ISSUE TITLE
Cannot change Lavarel environment variables after first call

### ISSUE THREAD

**Issue by OleksandrVladymyrov** [Codeception/Codeception#4062]
Hi!

Could you please help me to solve my problem. I write API and use Codeception to test it.
In some cases, I need to send 2 or more calls to API but before that, I should change Lavarel environment variables(LEV). When I try to set it at first all is OK and inside my code(at the controller) I have the value of  LEV the same as I set up. But after the first call(doesn't important method(get, post, ...)) the value of it takes on a default value. Below the part of code from the test:

        $I->getApplication()->make('config')->set(['test_value1' => 11]);

        $I->sendGET('/test');
        $I->seeResponseCodeIs(200);
        $I->seeResponseContainsJson([
            'error' => false,
            'data' => [
                0 => 11
            ]
        ]);

        $I->getApplication()->make('config')->set(['test_value1' => 15]);

        $I->sendGET('/test');
        $I->seeResponseCodeIs(200);
        $I->seeResponseContainsJson([
            'error' => false,
            'data' => [
                0 => 15
            ]
        ]);

As a result of the second query, I get
'data' => [
    0 => null
]

null -is the default value for this LEV

But I expected - 15

What do I make wrong?
Thanks in advance

**Comment by janhenkgerritsen** [comment]
Before a test runs the Laravel application object is initialized, and this also is the application object that is used for the first request in a test. 

However, to support multiple requests in a single test the application object is also re-initialized on each next request. You can see the relevant source code here:

https://github.com/Codeception/Codeception/blob/2.2/src/Codeception/Lib/Connector/Laravel5.php#L109

This means that the application object is reset during the second `$I->sendGET('/test');` call in your test, and that's why your config value change is not sticking.

To work around this problem you should create a separate test for each request.

**Comment by OleksandrVladymyrov** [comment]
First of all thanks for your quick answer.
Do you see a way to change LEV in the same test with a couple requests?

**Comment by janhenkgerritsen** [comment]
Not right now. But you are not the first one with a similar issue, so I'll probably implement something that can help in these types of situations. Currently I am thinking of a hook that will be called after the application object is initialized, either via an event or by registering closures. But I'll have to investigate that a bit to see if this will not create any new problems. So I cannot say when something like this will be implemented.

**Comment by OleksandrVladymyrov** [comment]
Thanks a lot.
I look forward to a speedy decision

**Comment by janhenkgerritsen** [comment]
I created a solution for this issue, please review and provide feedback :)

**Comment by OleksandrVladymyrov** [comment]
Thanks.
I used your solution and the goal was reached.
Perfect work :+1: :)

**Comment by janhenkgerritsen** [comment]
Ok, great!
