### ISSUE TITLE
PHP Fatal error:  Cannot declare class Symfony\Component\Finder\SplFileInfo, because the name is already in use 

### ISSUE THREAD

**Issue by RudyJessop** [Codeception/Codeception#4084]
Recently I ran into PHP Fatal error when  I run `vendor/bin/codecept run functional`.

This is what I get

```bash
Codeception PHP Testing Framework v2.2.10
Powered by PHPUnit 5.7.17 by Sebastian Bergmann and contributors.
PHP Fatal error:  Cannot declare class Symfony\Component\Finder\SplFileInfo, because the name is already in use in /var/www/bootstrap/cache/compiled.php on line 17063
```

I just recently started getting this error. If i run the acceptance or unit test suits it works fine.

I am using Laravel 5.3

**Comment by RudyJessop** [comment]
When I enable synfomy module I get an error (which i though would happen)

```bash
vagrant@corebox:/var/www$ php vendor/bin/codecept run functional
Codeception PHP Testing Framework v2.2.10
Powered by PHPUnit 5.7.17 by Sebastian Bergmann and contributors.


  [Codeception\Exception\ModuleConflictException]
  Symfony module conflicts with Laravel5
  --
  This usually happens when you enable two modules with the same actions but with different backends.
  For instance, you can't run PhpBrowser, WebDriver, Laravel5 modules in one suite,
  as they implement similar methods but use different drivers to execute them.
  You can load a part of module (like: ORM) to avoid conflict.
```

I would assume that symfony module is already attached to the Laravel5 module.

**Comment by janhenkgerritsen** [comment]
Have you tried deleting the `/var/www/bootstrap/cache/compiled.php` file?

**Comment by RudyJessop** [comment]
@janhenkgerritsen I did exactly that. To extend on what I did to fix this issue I removed and updated codeception. I believe there's a deeper problem than just removing a file. There's a name conflict somewhere in codeception and the symfony component

**Comment by janhenkgerritsen** [comment]
You need to provide some more information before we can help you with this issue, because now we don't have anything to go on. What composer packages do you have installed? Which versions of these packages? Can you replicate the issue in a new test project that you could share with us? And anything else you think can be of help.

**Comment by OwnerOfThisIsle** [comment]
I had the same issue.
After composer update it vanished, so I think it was solved in the meantime.

This is what composer did:

  - Updating twig/twig (v2.3.2 => v2.4.2): Downloading (100%)
  - Updating symfony/symfony (v3.3.0 => v3.3.2): Downloading (100%)
  - Updating phpunit/phpunit (6.1.4 => 6.2.1): Downloading (100%)
  - Updating codeception/codeception (2.3.2 => 2.3.3): Downloading (100%)
  - Updating consolidation/output-formatters (3.1.9 => 3.1.10): Downloading (100%)
  - Updating consolidation/robo (1.0.7 => 1.0.8): Downloading (100%)
  - Updating symfony/phpunit-bridge (v3.3.0 => v3.3.2): Downloading (100%)

But I can't tell if the problem was solved in symfony/phpunit-bridge or in codeception..
