### ISSUE TITLE
Test upload file with Codeception 2.2.10, RestApi, PhpBrowser (File is empty)

### ISSUE THREAD

**Issue by Elema82** [Codeception/Codeception#4173]
#3056 
 i try to create a test with:

codeception 2.2.10
guzzlehttp/guzzle 6.2.3
PhpBrowser
RestApi
My code is this:
```php
$files = [
            'file' => [
                'name' => 'image.jpg',
                'type' => 'image/jpeg',
                'size' => filesize(codecept_data_dir('image.jpg')),
                'tmp_name' => codecept_data_dir('image.jpg'),
                'error' => 0,
                   ]
        ];

        $I->wantTo('SendPost with $FILE');
        $I->haveHttpHeader("Authorization", "Bearer ".$I->getAccessToken());
        $I->haveHttpHeader('Content-Type', 'multipart/form-data');
        $I->haveHttpHeader("X-Company-Id", 4);

        $I->sendPOST('/tasks/7/attachments', [], $files);
        $I->seeResponseCodeIs(Response::HTTP_CREATED);
        $I->seeResponseIsJson();  
```
in my controller the variable $files is empty.

if remove this -> $I->haveHttpHeader('Content-Type', 'multipart/form-data');
not modified nothing.

but if change the version of guzzle to 5.* run ok and send file on post request

help!

**Comment by Naktibalda** [comment]
It doesn't make sense to use detailed file array syntax with Guzzle, because it actually performs a file upload over HTTP, so content of $_FILES is set by PHP on the server.

This syntax is documented, because earlier some or maybe even all framework modules didn't do any transformation and testers had to provide entire content of $_FILES array.
