### ISSUE TITLE
Which one is the "right" documentation for Symfony?

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#4243]
I see three different docs for Symfony:

* http://codeception.com/for/symfony
* http://codeception.com/09-04-2015/using-codeception-for-symfony-projects.html
* http://codeception.com/docs/modules/Symfony

What's the relation between these? Which one is "official"? What about merging them?

**Comment by DavertMik** [comment]
http://codeception.com/for/symfony - is the official. However, it was written 1 year ago and was not updated since then. 

http://codeception.com/docs/modules/Symfony - is about using Symfony module. This one evolves with a module but contains only brief reference

http://codeception.com/09-04-2015/using-codeception-for-symfony-projects.html - is a blogpost so it is not updated anymore, however it was the first attempt to write Symfony guide.

---

Do you have a Symfony project you want to test?

**Comment by ThomasLandauer** [comment]
> Do you have a Symfony project you want to test?

Yes!

I'd be willing to help merging these three. Probably the best place to have it would be the module. So my suggestion: Integrate the two others into the module, then delete them.  
But I need somebody to help me (i.e. answer questions).

**Comment by DavertMik** [comment]
@ThomasLandauer in the same time we are looking for the Symfony module maintainer :)
Can we connect in Skype, so I could answer all your questions? My Skype is: `davert.ua`
I'm also in Telegram and Facebook, but the Skype is better

**Comment by Naktibalda** [comment]
`/for/framework` was a cool new feature of Codeception 2.2 :)
