### ISSUE TITLE
Documentation should be moved from the code to markdown

### ISSUE THREAD

**Issue by c33s** [Codeception/Codeception#4299]
to better add more documentation and also have the better markdown syntax highlighting, it would make sense to move the module docs from the php doc block to a markdown file

**Comment by DavertMik** [comment]
No, it should not. 

It already has markdown syntax. 
It doesn't make sense to keep docs out of source files because they will become unsynchronized really fast. The documentation is the essential part of the code and should be kept there as well. Despite it make files longer, it should be in the same file.
