### ISSUE TITLE
PhpSuperGlobalsConverter and UploadedFile size not int

### ISSUE THREAD

**Issue by Y0lk** [Codeception/Codeception#4461]
When using the remapFiles() method, all the values inside the files array are turned into strings. This is because of the result of the replaceSpaces() method.

This is especially a problem with the "size" value of uploaded files. The size parameter is supposed to be an int, so frameworks who implement the PSR-7 UploadedFileInterface expect the size parameter to be an int.

In my case, I was building a custom Codeception Framework module for a custom framework that uses Zend Diactoros to process requests. Zend Diactoros' UploadedFile throws an exception if the size is not an int, so it breaks.

**Comment by Naktibalda** [comment]
You don't have to use it.
Only [4 out of 9](https://github.com/Codeception/Codeception/search?utf8=%E2%9C%93&q=PhpSuperGlobalsConverter&type=) bundled framework modules use PhpSuperGlobalsConverter.

ZendExpressive [connector](https://github.com/Codeception/Codeception/blob/29635bf268dc70705388adeed85d69fdd3553d1e/src/Codeception/Lib/Connector/ZendExpressive.php) converts BrowserKit Request to Diactoros ServerRequest, however I have to admit that I haven't tested if it suffers from any issues supposedly fixed by PhpSuperGlobalsConverter.

**Comment by Y0lk** [comment]
Yeah, but the methods are useful. As a workaround for now, I just use rearrangeFiles instead of remapFiles, but I thought it was good to point that out. Since some values inside the $_FILES array are set by php (like 'size'), those probably shouldn't go through the replaceSpaces method.

I haven't tried with other frameworks to be honest but I'm surprised it hasn't caused any problems before.
