### ISSUE TITLE
Suggestion for Doctrine2 Module: refresh()

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#4526]
It looks like, if an entity gets modified by the app, there's no cool way to refresh it in Codeception.

Sample pseudo code:
```php
$user = $I->grabEntityFromRepository(...);
$I->assertTrue($user->isActive());
$I->submitForm(...); // some form which changes the user to inactive
// This fails, since `$user` is still the same as above:
$I->assertFalse($user->isActive());
```

Right now, I can't think of any other way than to reload the entity from the database, which means repeating the first line:
```php
// ... 
$modifiedUser = $I->grabEntityFromRepository(...); // same as in line 1 above
$I->assertFalse($modifiedUser ->isActive());
```

But something like this would be nicer:
```php
// ... 
$I->refreshEntity($user); // would be cool :-)
$I->assertFalse($user ->isActive());
```

### Details

* Codeception version: 2.3.5
* PHP Version: 7.1

**Comment by mariusz-kraj-c** [comment]
👍

**Comment by alexkunin** [comment]
I'd add that doing another `grabEntityFromRepository()` call won't help because entity manager has no reasons to think its cache is invalid, and it will just return same object as before with all fields having old values.

Doing `$entityManger->refresh($entity)` would really help.

Doing `$entityManager->clear()` would also help, but in a bit different way:

- it detaches all entities from manager, so, all previously retrieved entities won't be updated
- but all `grab*()` methods will result in new entities retrieved, and they will have updated field values

I think both ways might work in different situations. Going to prepare a PR for this.
