### ISSUE TITLE
Exceptions from _before of modules are catched

### ISSUE THREAD

**Issue by zuozp8** [Codeception/Codeception#4540]
#### What are you trying to achieve?
I'd like to avoid running tests when starting transaction failed.

When [Codeception\Module\Yii2::_before()](https://github.com/Codeception/Codeception/blob/2.3.5/src/Codeception/Module/Yii2.php#L169) fails with exception, it doesn't stop the tests from running. It broke my test environment: usually module was wrapping tests in transaction, so that I could do anything with db inside my test and it wasn't commited.

The suspicious code is in [\Codeception\PHPUnit\Listener::startTest()](https://github.com/Codeception/Codeception/blob/2.3.5/src/Codeception/PHPUnit/Listener.php#L88) - I suspect catching 'PHPUnit_Framework_IncompleteTestError'/'PHPUnit_Framework_SkippedTestError' is pointless too

### Details

* Codeception version: 2.3.3
* PHP Version: 7.1
* Operating System: ubuntu

**Comment by Naktibalda** [comment]
That code fixed a fatal error: #3653

We have a test for it: https://github.com/Codeception/Codeception/blob/2.3.5/tests/cli/ExceptionInBeforeDoesNotMakeFatalErrorCept.php

Exception in _before stops test execution in Cept, Cest and Gherkin formats, it doesn't stop execution of Test format, because it is executed by PhpUnit and we have no control over it.
