### ISSUE TITLE
HTML Reports: BDD Given/When/Then are not included in the test steps

### ISSUE THREAD

**Issue by ShazzamaPajama** [Codeception/Codeception#4550]
#### What are you trying to achieve?
HTML reports provided by Codeception list the steps of each test provided in a BDD .feature file. It would be very useful to provide more context to these reports by applying  Given / When /Then before each step in the HTML report, just as it looks in the .feature file.

Reporting features of other BDD implementations such as Cucumber-jvm provide the Given/When/Then contexts before each step in their html reports. 

This will provide more context in the reporting feature. BDD is supposed to provide a common language around testing that an entire team can understand. It would be useful if this language extended to our reports as well.

#### What do you get instead?
The HTML report only lists the base text of the step definition.
```
Feature: Login

  Scenario: successfully sign into the application
      Given A user account has been created
      And I am on the Neo login page
      When The user signs into the Neo application
      Then The Neo dashboard page is visible

```

![image](https://user-images.githubusercontent.com/4267709/31180269-3262f1a0-a8ec-11e7-87dc-7becd0f5093f.png)

**Comment by DavertMik** [comment]
Thanks for the suggestion. We will work on this

**Comment by eXorus** [comment]
I'm closing this issue because it has been fixed.

<img width="571" alt="Capture d’écran 2021-01-18 à 13 35 46" src="https://user-images.githubusercontent.com/1255561/104916280-21142e00-5992-11eb-821d-ea5ee568fb64.png">
<img width="694" alt="Capture d’écran 2021-01-18 à 13 35 34" src="https://user-images.githubusercontent.com/1255561/104916282-21acc480-5992-11eb-982f-6e3daf7e7cde.png">
