### ISSUE TITLE
Codeception + Jenkins - XML report doesn't work :( Help! 

### ISSUE THREAD

**Issue by Sashan777** [Codeception/Codeception#4639]
Jenkins + codeception 2.2.12  + selenium-standaloneserver
there is my settings and results... what am i doing wrong?

![image](https://user-images.githubusercontent.com/31503247/33071659-75adbdb2-cecd-11e7-97ad-630e4ed8f64b.png)

![image](https://user-images.githubusercontent.com/31503247/33071601-342c9ae8-cecd-11e7-914d-b85b513f3bd3.png)

![image](https://user-images.githubusercontent.com/31503247/33071671-85141b8e-cecd-11e7-9d30-741612571cae.png)

**Comment by Naktibalda** [comment]
It looks like publishHtml moves the files.
My advice is to change order of steps to publish xunit results first (that's how I got it in my Jenkinsfile).

**Comment by Sashan777** [comment]
Thnks! I changed levels of steps - publish xunit first then HTML, but it's doesn't help me... same error
can't get my xml report;(

**Comment by rebas82** [comment]
working this:
vendor/bin/codecept run  --html report_${JOB_NAME}_${BUILD_TIMESTAMP}.html --xml report_${JOB_NAME}_${BUILD_TIMESTAMP}.xml --no-exit

tests/_output/report_${JOB_NAME}_${BUILD_TIMESTAMP}.xml

**Comment by reinholdfuereder** [comment]
I claim the original problem was that the reports were generated to "/codecept/..." instead of in the Jenkins workspace "/home/jenkins/work/workspace/...", and while HTML publishing was correctly configured, the xUnit one referenced the Jenkins workspace:
![image](https://user-images.githubusercontent.com/145182/54417546-cb6dfb00-4702-11e9-91ba-145fda01d9c5.png)

@Naktibalda Would you mind closing this issue?

**Comment by Naktibalda** [comment]
Thanks
