### ISSUE TITLE
I have error 

### ISSUE THREAD

**Issue by not91** [Codeception/Codeception#4876]
TypeError with message: Argument 3 passed to Codeception\Event\FailEvent::__construct() must be an instance of Exception, instance of Error given, cal
led in vendor/codeception/phpunit-wrapper/src/ResultPrinter/UI.php on line 28

### Details

* Codeception version: 2.4
* PHP Version: 7.1
* Operating System: Linux Ubuntu
* Installation type: Composer
* Module Yii2

**Comment by edno** [comment]
@not91 - Please provide the full console output using `-vvv` and if possible the test case related to this issue.

**Comment by Druid33** [comment]
Hi, codeception v2.3 works fine for me.

composer show output:
<pre>
behat/gherkin                      v4.4.5 Gherkin DSL parser for PHP 5.3
codeception/codeception            2.3.0  BDD-style testing framework
doctrine/instantiator              1.1.0  A small, lightweight utility to instantiate objects in PHP without invoking their constructors
facebook/webdriver                 1.3.0  A PHP client for WebDriver
filp/whoops                        2.1.14 php error handling for cool kids
guzzlehttp/guzzle                  6.3.3  Guzzle is a PHP HTTP client library
guzzlehttp/promises                v1.3.1 Guzzle promises library
guzzlehttp/psr7                    1.4.2  PSR-7 message implementation that also provides common utility methods
myclabs/deep-copy                  1.7.0  Create deep copies (clones) of your objects
phpdocumentor/reflection-common    1.0.1  Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  4.3.0  With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver        0.4.0  
phpspec/prophecy                   1.7.6  Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          4.0.8  Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          1.4.5  FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1  Simple template engine.
phpunit/php-timer                  1.0.9  Utility class for timing
phpunit/php-token-stream           2.0.2  Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    5.7.27 The PHP Unit Testing framework.
phpunit/phpunit-mock-objects       3.4.4  Mock Object library for PHPUnit
psr/http-message                   1.0.1  Common interface for HTTP messages
psr/log                            1.0.2  Common interface for logging libraries
sebastian/code-unit-reverse-lookup 1.0.1  Looks up which function or method a line of code belongs to
sebastian/comparator               1.2.4  Provides the functionality to compare PHP values for equality
sebastian/diff                     1.4.3  Diff implementation
sebastian/environment              2.0.0  Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 2.0.0  Provides the functionality to export PHP variables for visualization
sebastian/global-state             1.1.1  Snapshotting of global state
sebastian/object-enumerator        2.0.1  Traverses array structures and object graphs to enumerate all referenced objects
sebastian/recursion-context        2.0.0  Provides functionality to recursively process PHP variables
sebastian/resource-operations      1.0.0  Provides a list of PHP built-in functions that operate on resources
sebastian/version                  2.0.1  Library that helps with managing the version number of Git-hosted PHP projects
stecman/symfony-console-completion 0.7.0  Automatic BASH completion for Symfony Console Component based applications.
symfony/browser-kit                v3.4.9 Symfony BrowserKit Component
symfony/console                    v3.4.9 Symfony Console Component
symfony/css-selector               v3.4.9 Symfony CssSelector Component
symfony/debug                      v4.0.9 Symfony Debug Component
symfony/dom-crawler                v3.4.9 Symfony DomCrawler Component
symfony/event-dispatcher           v3.4.9 Symfony EventDispatcher Component
symfony/finder                     v3.4.9 Symfony Finder Component
symfony/polyfill-mbstring          v1.8.0 Symfony polyfill for the Mbstring extension
symfony/process                    v3.4.9 Symfony Process Component
symfony/yaml                       v3.4.9 Symfony Yaml Component
webmozart/assert                   1.3.0  Assertions to validate method input/output with nice error messages.
</pre>

**Comment by Naktibalda** [comment]
Fixed by #4978 
@DavertMik It is a yet another good reason to make a new release.
