### ISSUE TITLE
How about W3C standard for selenium?

### ISSUE THREAD

**Issue by bscheshirwork** [Codeception/Codeception#4898]
#### What are you trying to achieve?
acceptance tests still work

#### What do you get instead?
acceptance tests not work on fresh selenium

https://github.com/SeleniumHQ/docker-selenium/issues/675
https://github.com/SeleniumHQ/docker-selenium/issues/697

> Selenium and the drivers(ChromeDriver in this case) on the server side is iterating on every release to adjust more to the W3C standard, and if you check the official bindings, they also iterating to adjust to the W3C specifications. Nevertheless, in some cases 3rd party bindings (like PHP) are not adjusting as fast as the official ones.

**Comment by DavertMik** [comment]
The only thing we can do is to help https://github.com/facebook/php-webdriver project. It really needs some help to follow up with recent Selenium changes.

**Comment by bscheshirwork** [comment]
https://github.com/facebook/php-webdriver/issues/469#issuecomment-377493943

**Comment by DavertMik** [comment]
Exactly. If we want to see it happen we need to help @OndraM to implement it. 
No magic out there. And btw, facebook/php-webdriver is not sponsored by facebook anymore, so yes, it's totally volunteer project and you can provide some help improving it.

**Comment by DavertMik** [comment]
Closing this as it's really not our issue

**Comment by reinholdfuereder** [comment]
@DavertMik and @Naktibalda Can it be that now due to Chrome v75 things are getting serious: cf. https://github.com/facebook/php-webdriver/issues/469#issuecomment-499497795

However @andrewnicols gives me hope: https://github.com/facebook/php-webdriver/issues/469#issuecomment-499506260

**Comment by andrewnicols** [comment]
I’ll push my work tomorrow (Australian here)

**Comment by andrewnicols** [comment]
Took me longer than I had hoped, but I've gotten to a point where _most_ things are working in https://github.com/andrewnicols/php-webdriver/tree/fixtheworld

I still have a list of things not yet working (GET_ELEMENT_LOCATION_ONCE_SCROLLED_INTO_VIEW is not available in W3C Webdriver for example) and I discovered that the window API has changed.

**Comment by OndraM** [comment]
Change of the default protocol in Chromedriver 75 was met with [a bug](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2943) causing click and other actions to not work, even with disabled W3C protocol.

There is now workaround in https://github.com/facebook/php-webdriver/pull/640 and we hope to get it released ASAP in php-webdriver.

And I hope works on W3C implementation will follow :).

**Comment by reinholdfuereder** [comment]
Just for the sake of completeness/traceability and also because of  [request for comments by core Codeception developers](https://github.com/facebook/php-webdriver/issues/657#issuecomment-518222916) (presumably @DavertMik and @Naktibalda):
* Please see Ondrej's recent "kick-off" issue: https://github.com/facebook/php-webdriver/issues/657

**Comment by reinholdfuereder** [comment]
@DavertMik and @Naktibalda (and @OndraM): Sorry for the following possibly very naive/dumb question:

Due to https://github.com/Codeception/module-webdriver/releases/tag/1.0.1 and https://github.com/Codeception/module-webdriver/commit/0f65824b66269a7a9feee2c97554b241ecde81b2 there is `"php-webdriver/webdriver": "^1.8.0"`, and according to https://github.com/php-webdriver/php-webdriver/blob/main/CHANGELOG.md#180---2020-02-10 there is "_Experimental W3C WebDriver protocol support_"

**=> Thus is the W3C protocol now (or already for quite some time?) supported by Codeception?**

**Comment by OndraM** [comment]
Yes, it should already be supported for a while, since the release of php-webdriver 1.8.0 and gradually getting improved in following versions.

And in fact, W3C is also the default protocol in ChromeDriver for over two years. And GeckoDriver support only W3C protocol from the beginning.
