### ISSUE TITLE
Unit tests without DB

### ISSUE THREAD

**Issue by josephzidell** [Codeception/Codeception#5012]
#### What are you trying to achieve?
Better performance for certain unit tests that do not need the database. 

#### What do you get instead?
The Db module either cleans up every time or never, depending on the configuration.

#### PR
The idea is simple and requires a one-line PR that I'd be happy to make.

Test:
```php
	/**
	 * @disableDbCleanup
	 *
	 * @return void
	 */
	public function testTextInputBasic() {...}
```

src/Codeception/Module/Db.php
```diff
     public function _before(TestInterface $test)
     {
         if ($this->config['reconnect']) {
             $this->connect();
         }
-        if ($this->config['cleanup'] && !$this->populated) {
+        if ($this->config['cleanup'] && !$this->populated && empty($test->getMetadata()->getParam('disableDbCleanup'))) {
             $this->_cleanup();
             $this->_loadDump();
         }
         parent::_before($test);
     }
```

If people like this idea, we can extend it by allowing it on the class with another one-liner.

**Comment by josephzidell** [comment]
Perhaps a clearer annotation would be `@skipDbCleanup`

**Comment by johannesschobel** [comment]
can you provide a PR for this feature? I think, this may be useful in certain situations..
I would, however, go for a more cleaner / meaningful annotation, as you already suggested..

The only issue i see, however, is, that this feature **highly** depends on the ORDER how tests are executed. I can imagine, that you would apply this annotation in order to better structure your tests (and make them incremental). However, if you "insert" a test inbetween (or the execution of the runner changes!!!!) this may become a **huge** problem..

What is your opinion on this?!

**Comment by josephzidell** [comment]
@johannesschobel I'll get the PR.
My understanding of `_before()` is that it's run for each test method, thereby evaluating this condition anew. Am I wrong?

**Comment by johannesschobel** [comment]
Yes.. However if you don't clean the DB before the test, your test may be wrong..

Consider the following example..
You have a test for registering a new user, that passes.. next you execute a test that returns all users. This test is annotated with the introduced `skipDB`. The `count` of the returned users would be `n+1` (because of the create it test that was executed before)..

If you revert the test order, the `count` would be `n`..

**Comment by josephzidell** [comment]
I may have explained the intended usage wrong. The purpose is for tests that don't use the DB. For example, how would you test pure PHP code that doesn't use SQL?

**Comment by johannesschobel** [comment]
Aaaaaah.. now I get it..
Then, however, I think, the annotation name is misleading..

**Comment by josephzidell** [comment]
Do you have any ideas?

**Comment by josephzidell** [comment]
How about `@skip db.cleanup`? This format would allow for expansion to (theoretically) and feature in any module.

**Comment by Naktibalda** [comment]
It is the best to move tests that consume database to another suite.
