### ISSUE TITLE
REST with automatic OPTIONS

### ISSUE THREAD

**Issue by rinu** [Codeception/Codeception#5170]
#### What are you trying to achieve?
My application provides a REST API that is used directly from the browser. It would be nice to have a general setting for a test suite or an individual test that will send an OPTIONS request before for example a GET or a POST even when I don't use `sendOPTIONS` in that test. It would then assert the response to make sure I'm allowed to make the actual request.

To achieve this at the moment, every single test must do `sendOPTIONS` before the actual request and check the response. This is too easy to forget and looks like bloat.

* Codeception version: 2.3.9
* PHP Version: 7.x
* Operating System: Ubuntu
* Installation type: Composer

**Comment by SamMousa** [comment]
From a security perspective you should not rely on CORS since only browsers implement this, but any client can use your API.

Asserting that you are allowed to do something is a test of itself and if you write a test for it you can have your other tests depend on that one.

**Comment by rinu** [comment]
I don't need this for security, and don't worry, there are other means in place. The application forces the developer to think about OPTIONS for every single request, it's not enabled by default. All I need is to make sure the developer hasn't forgotten to do that.

Can you provide examples or links? I'm not sure how I could make tests that depend on each other. I actually attempted a hack where I send OPTIONS before every request but the responses got mixed up or something and it was a mess. Maybe it's just that I couldn't figure out how multiple requests per test work.

**Comment by SamMousa** [comment]
But why do you need to send an `OPTIONS` request at all?

> Can you provide examples or links?

I think it's `@depends` or `@before` notation.

**Comment by rinu** [comment]
I need to send it to check if it's implemented (correctly).

`@depends` doesn't seem appropriate. I can't provide any information (URL for example) to it.

I might have requests like these in my API
* GET /users
* GET /users/{id}
* POST /users
* PUT /users/{id}
* DELETE /users/{id}

Each of these is tested in a different test. Before the first I would have to verify that `OPTIONS /users` returns with status code 200 and the accepted methods include GET. Before the second verify `OPTIONS /users/{id}` returns status code 200 and includes GET. And so on.

Then I might also have tests that check for errors. For example before `PUT /users/{invalid-id}` I would want to verify that `OPTIONS /users/{invalid-id}` returns status code 404.

**Comment by SamMousa** [comment]
> Before the first I would have to verify that OPTIONS /users returns with status code 200 and the accepted methods include GET.

Why? If that's not the case then just doing GET will return 405...
The whole point if a REST API is that it is stateless, so your requirement to do one test before another seems counter intuitive.

You can just create a data provider for the options test and provide all URLs with their expected supported methods. Then the tests code that tests it for all URLs becomes very trivial.

**Comment by rinu** [comment]
It doesn't return 405 if I do just GET. The tests are not running from a browser.

**Comment by SamMousa** [comment]
So what are you testing then.... You do OPTIONS on a URL the response tells you you cannot do a GET; you ignore the advice and do it anyway and it works?!

I'd love an explanation of this architecture that randomly doubles the number of requests to its API for no obvious reason. Why would I do an OPTIONS before a GET if I can just do the GET?

**Comment by rinu** [comment]
The tests are running from the command line. The real world use case for the application is from the browser. Browsers will not allow cross-origin GET requests before making sure it's allowed by the server and automagically uses OPTIONS for it.

**Comment by SamMousa** [comment]
Yes, that's CORS.
But testing that OPTIONS return the correct response is something you could do with a dataprovider that first checks the OPTIONS request for all URLs.
Alternatively create a helper function if you really want to.
 
Also, these OPTIONS requests in browsers don't happen for GET requests.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests

Also these CORS headers can be passed back in any simple request.
Given that you are building an API that has no session cookie (since it uses REST) you could just allow everything from a CORS perspective.

**Comment by rinu** [comment]
Finally we get back to the whole point. I am already using a data provider to check all URLs and it works just fine. What I was initially asking for is not having anything at all. I want a mode that simulates the browser, sends OPTIONS and checks the response, all without me even knowing about it, unless it fails or course.

We're not only talking about GET, there's a long list. For whatever reason, my browser also does preflight for GET. I don't care why, let's not go into that right now.

The whole reason CORS is not allowed for everything is because it shouldn't be. There is a part of the API that you actually need to open in a new window/tab and interact with it directly.

**Comment by rinu** [comment]
I see a WebDriver module but there's no mention of these features. I would have to rewrite all tests if it's added there, currently using REST module.

**Comment by jmurowaniecki** [comment]
@rinu #TMJ
![I know that feel bro](https://i.kym-cdn.com/photos/images/newsfeed/000/107/432/i_hug_that_feel.png)

I'm using OPTIONS too but not to only support CORS or inform acceptable methods. I'm using it to enhance documentation returning accepted body formats, attributes and schemas.

![Available REST routes](https://user-images.githubusercontent.com/1261167/53650496-740c5d00-3c23-11e9-95d9-4999d526e3d9.png)

With this I can provide realtime help in a `sandbox like way` for developers using nothing more than cURL, or another tool.. Also it enables me to generate self-validation and generic acceptance testing - since it gives me a list of every endpoint and data structure to every method request and response for validation.

This way I can generate automatically content for Postman/Apiary/PutHereYourFavoriteBluePrintLikeParser easy peasy without having to struggle with lots of specific validation for something I can predict while develop.

![Codeception output](https://user-images.githubusercontent.com/1261167/53651151-cbf79380-3c24-11e9-860f-9f13e0fe9e73.png)

For now I really need to execute an OPTIONS request for each other request, even though this is done by the Angular frontend and we use a token validating the requests - likewise preventing the loading of the structures in each response by setting in the send header a key.

**Comment by Naktibalda** [comment]
If making OPTIONS requests looks repetive in your tests, it could be useful to implement custome wrappers for sendGet/sendPost/etc and make them do OPTIONS requests first.

This functionality doesn't look like good feature for REST module.
