### ISSUE TITLE
Connector\Yii2\BaseMailer incompatible with yii2-queue because of "[Exception] Serialization of 'Closure' is not allowed"

### ISSUE THREAD

**Issue by thyseus** [Codeception/Codeception#5290]
In Codeception 2.5.0 the BaseMailer has introduced using a callback(closure) to set the
 messages-to-be-tested.
In Codeception 2.4.5 and below this was different and no closure was used.

We are using yii2-queue to sent Emails through a queue. The SwiftMailer Object is being serialized in the queue. When running the tests, we get the following error:

```
                                                       
  [Exception] Serialization of 'Closure' is not allowed  
                                                         
#1  /var/www/vendor/yiisoft/yii2-queue/src/serializers/PhpSerializer.php:24
#2  /var/www/vendor/yiisoft/yii2-queue/src/Queue.php:161
[...]
```

Do you have any idea how to make the new (mocked) BaseMailer compatible with yii2-queue? 
Is this problem already known?

Thanks a lot for any advices or workarounds.
### Details

* Codeception version: 2.5.0 (2.4.5 and below are working)
* PHP Version: 7.2
* Operating System: Linux
* Installation type: Composer

**Comment by SamMousa** [comment]
There is a closure being added in `TestMailer`, which extends `BaseMailer`.
`BaseMailer` itself also has a closure, `$fileTransportCallback`.

Regardless of where this closure is located I think the question is wrong.

> Do you have any idea how to make the new (mocked) BaseMailer compatible with yii2-queue?

Yes. Do not serialize components. Components offer a service and you have no idea if they support serialize or not. 
If you want to serialize the message (assuming the implementation you use is close to `BaseMessage`), unset the public `$mailer` property before serializing it.
Then, when sending, pass it a mailer to use (or have it fallback to the component named `mailer` in the application).

This is not an issue of Codeception. 
It is an issue with Yii2 in the sense that a domain object (message) should not have a reference to a 
service.

The generic way in which I solve is this:
1. I know that a mailer will send anything that implements a `MessageInterface`.
2. I know I have an instance of some class that implements a `MessageInterface`.
3. I implement class `SerializeMessage`:
```php 

class SerializeMessage implements MessageInterface {
    private $property1;
    public function __construct(MessageInterface $message)
    {
        $this->property1 = $message->getProperty1();
    }

    public function getProperty1()
    {
        return $this->property1;
    }
}
```
4. Since this is a known implementation I can serialize it safely.
5. In my queue runner I can deserialize it and pass it on to any mailer which will happily send it.


Closing this as it is not an issue.

**Comment by SamMousa** [comment]
Side note: the added benefit is that you will no longer be exposing your SMTP server password in your queues' jobs.

**Comment by thyseus** [comment]
@SamMousa thanks a lot for your elaborated answer. I consider improving my Code. :+1:  :smile:

**Comment by thyseus** [comment]
For people that are interested in this issue: The improved code can be found here:

https://gitlab.com/thyseus/yii2-message/commit/321b069ef831cf6f1b45c6699c14fd2ec15054ff

Thanks again, @SamMousa  for your help, its working like a charme!
