### ISSUE TITLE
Codeception with virtual host?

### ISSUE THREAD

**Issue by jijoel** [Codeception/Codeception#533]
I'm having an issue trying to get basic testing in codeception to work for my wamp system. I copied codecept.phar to my project folder, then ran `php codecept.phar bootstrap`, `php codecept.phar generate:cept acceptance First`, and `php codecept.phar build`.  codeception.yml is set to the default. acceptance.suite.yml is set to this:

```
class_name: WebGuy
modules:
    enabled:
        - PhpBrowser
        - WebHelper
    config:
        PhpBrowser:
            url: 'http://test/'
```

'test' is set up as a virtual host. I can go there in any browser, and wget, and curl. My acceptance test is pretty simple:

``` php
<?php
$I = new WebGuy($scenario);
$I->amOnPage('/test.php');
$I->see('foo');
```

This is basically the "hello, world" of testing, but I can't seem to get it to work. I get a failure that:

> 404 Not Found Not Found The requested URL /hex.php was not found on this server.

I can reach http://test/test.php via every other avenue I've tried. It's a pretty simple script, too:

``` php
<?php
echo 'foo';
```

I'm pretty new to this, and completely stumped. Any ideas what I could be doing wrong, or ideas about things I could check?

Thank you!

--joel

EDIT: I discovered that it's doing the same thing on my (home) linux computer, with very different configuration. I wonder if I'm missing something fundamental. I set up a temporary github project with what I have at https://github.com/jijoel/delete-codecept-test.

**Comment by DanielBoettner** [comment]
Thank you @jijoel 
Even though your last comment dates back to 2013 this was an incredible useful bit of information.

Folloing explanation is mainly added (for google) to help others maybe finding this solution.

I did spend almost 3 days trying to get a simple acceptance test to run inside a docker container.
in order to use the container in CI/CD pipelines.

I failed with several containers, running either alpine linux 3.5 nginx/php7.1 or alpine/apache2/php7.
Even tried an unnecessary bloated ubuntu/apache2/php7. becaue I thought there repos and packages are maybe better maintained than the alpine ones.

I tried different stuff:

like the changing the _listen_ configuration from **127.0.0.1:9000** to **/var/run/php/php-fpm.sock**, ignoring invalid headers, different CURL_OPT header settings, switching to apache2.
When I opened the machine in my browser the page was visible. phpBrowser failed with either 400 or 500 (depending on the configuration).

In the end simpy adding the port in the yml file was the solution. Maybe there it was a combination of several configuration issues and the port. Anyway, thank you again.
