### ISSUE TITLE
Error using an array as object in the loading Session Snapshot

### ISSUE THREAD

**Issue by samuelfa** [Codeception/Codeception#5456]
#### What are you trying to achieve?
When codeception try to load a session snapshot previously stored in other test, the code fail because the system except that the property "$this->sessionSnapshots[$name]" is filled with instances of some class when is filled with associative arrays

#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

FATAL ERROR. TESTS NOT FINISHED.

Call to a member function getName() on array 
in /var/www/html/vendor/codeception/codeception/src/Codeception/Module/WebDriver.php:3108

A few lines before we can see the following code (lines 3081  to 3089):

```php
foreach ($this->webDriver->manage()->getCookies() as $cookie) {
            if (in_array(trim($cookie['name']), [LocalServer::COVERAGE_COOKIE, LocalServer::COVERAGE_COOKIE_ERROR])) {
                continue;
            }

            if ($this->cookieDomainMatchesConfigUrl($cookie)) {
                $this->sessionSnapshots[$name][] = $cookie;
            }
        }
```

The property sessionSnapshots is filled with the variable $cookie, provided by $this->webDriver->manage()->getCookies() and the getCookies return an associative array.

```php
    /**
     * Get all the cookies for the current domain.
     *
     * @return array The array of cookies presented.
     */
    public function getCookies()
    {
        return $this->executor->execute(DriverCommand::GET_ALL_COOKIES);
    }
```
### Details

* Codeception version: 2.5.5
* PHP Version: 5.6.39
* Installation type: Composer

**Comment by reinholdfuereder** [comment]
Which browser type and version, and which WebDriver type and version do you use? Based on @Naktibalda's comment in https://github.com/Codeception/Codeception/pull/5404#issuecomment-475877275 I naively guess it is Chrome >= 72 with ChromeDriver >= 2.46?

**Comment by Naktibalda** [comment]
Using `$cookie['name']` instead of getName would work in both cases, because Cookie class implements ArrayAccess interface.
Please make a pull request.

**Comment by Naktibalda** [comment]
I got objects when I was testing, I wonder if it depends on version of facebook/php-webdriver. What version have you got installed?

**Comment by samuelfa** [comment]
Hi @Naktibalda.
I saw that my composer.json required the 1.3.0 version of facebook/webdriver, then I just fix the problem updating the version of facebook/webdriver from 1.3.0 to the last version (1.6.0).
I see in the [changelog](https://github.com/facebook/php-webdriver/blob/community/CHANGELOG.md) that the minimal version that supports the Cookie object is the 1.4.0.

I think that the composer.json requirement should be change to use as minimal version 1.4.0 or change the code again to use the array access style.

Thank you!

**Comment by reinholdfuereder** [comment]
Actually in codeception 2.5 branch the "composer.json" specifies:
`"facebook/webdriver": ">=1.1.3 <2.0",`
* @samuelfa I am even more confused as before ;-): Where do you have the "1.3.0" version specification? And/or why is not the newest version "<2.0" of "facebook/webdriver" and thus 1.6.0 used?

By contrast codeception 2.6 branch already specifies:
`"facebook/webdriver": "^1.6.0",`
... but only since Mar 2, 2019 (and commit https://github.com/Codeception/Codeception/commit/f6c71986e08e6a30a5423434a9363f40df3594d5#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780).

Considering (a) the lack of any changes in "facebook/webdriver" since Oct 18, 2018 and (b) the release of version 1.6.0 of "facebook/webdriver" on 2018-05-16 I think that is more than safe to jump to that version also in codeception 2.5. What do you think @Naktibalda?

@Naktibalda Last but not least I dare to ask another very dumb and only semi-related question: How is the "codecept.phar" file actually built?

**Comment by Naktibalda** [comment]
There was no reason to support older versions of php-webdriver in Codeception 2.5.

1.1.3 was the last version of php-webdriver which supported PHP 5.4.
Support for PHP 5.4 was dropped in Codeception 2.5, but composer constraints weren't updated until I started preparing the next release.

Updating composer.json in 2.5 is not a solution, because instead of forcing user to upgrade php-webdriver, composer keeps the last version of codeception compatible with php-webdriver 1.3.0.

There will be no more releases of 2.5 branch, unless some serious issue is discovered.

codecept.phar is build using [Robo](https://robo.li/):

https://github.com/Codeception/Codeception/blob/2.5/RoboFile.php#L134-L267

**Comment by reinholdfuereder** [comment]
@Naktibalda thanks for the explanations (and patience)

Looking forward to the first Codeception 2.6 release then ;-)
* which does allow resolving this issue here, doesn't it?
* and which I guess/hope will also contain:
    * nice new features/enhancements like: retries, PHPUnit 8.x, ...
    * fix for https://github.com/Codeception/Codeception/issues/4413 via https://github.com/Codeception/phpunit-wrapper/pull/62
