### ISSUE TITLE
$I->seeElement required html tag? 

### ISSUE THREAD

**Issue by cosinus90** [Codeception/Codeception#5556]
I have AJAX endpoint that returns html markup of the items loaded on the page scroll. This isn't a jquery and isn't a full HTML document which I mean starts from HTML tag. My endpoint returns items that later will be included in the document like

`$('#id').append(html);`

I guess it's a common situation. But when I try to test this result for an element - it fails:

```
$I->sendAjaxRequest('POST', '/channel/search?sort_column=false&sort_dir=false', [...]);
$I->seeElement('.offset');
```

First line of AJAX response is 

````
 <tr class="offset" data-offset="10" ></tr>
````

Looks like the seeElement function (and others) require the HTML document starting from HTML tag? Is there any possibility to test the response in my case?

**Comment by Naktibalda** [comment]
You could use [seeInSource](https://codeception.com/docs/modules/PhpBrowser#seeInSource) to match a bit of HTML.
```php
$I->seeInSource('<tr class="offset"');
```

**Comment by ThomasLandauer** [comment]
So what are the exact requirements for `seeElement()` to work? And does the same apply to `$I->see('...', [XXX])` as well?

**Comment by Naktibalda** [comment]
How does it fail?

**Comment by ThomasLandauer** [comment]
```php
$I->sendAjaxPostRequest(...);
$I->seeElement(['css' => 'form']);
```
fails with:
> Step  See element {"css":"form"}
> Fail  Element located either by name, CSS or XPath element with '"css":"form"' was not found.

**Comment by ThomasLandauer** [comment]
Just did some testing with `see()`:
* When I just pass the string (`see('foo');`), it works.
* When I also pass a CSS selector (`see('foo', ['css' => '.class']);`), it does never work - no matter if the Ajax response has an `<html><body>` skeleton or not.

**Comment by Naktibalda** [comment]
I looked into this, and I think that it is a bug that any assertion sees response of Ajax request.

As far as I remember, the intention was that Ajax methods make requests that cause some side effects in backend, e.g. update database record, but the browser stays on the same page where it was before making Ajax request and the test can `click` or `submitForm` on that page.

@DavertMik Can you confirm that?

**Comment by DavertMik** [comment]
`sendAjaxRequest` was one of the first methods introduced to Codeception to test my project I worked on in 2012. The fun fact it didn't change much since that time.

Originally, it was dealing with HTML responses because our site used to display popups via HTML.

I may assume that nowadays underlying parser doesn't understand HTML without `<html>` tag, so this problem can be very hard to solve. Should we wrap response in `<html>` ? 

Anyway, there are less and less applications using Ajax approach, so I think this is minor issue.
But if someone comes with Pull Request to InnerBrowser which wraps HTML responses with HTML tag, I am ok to accept it.
(or any other solution to this issue).
