### ISSUE TITLE
[Doctrine2] haveInRepository does not support constructor parameters

### ISSUE THREAD

**Issue by burned42** [Codeception/Codeception#5632]
#### What are you trying to achieve?
Call `$I->haveInRepository()` of the "Doctrine2" module with an entity which expects constructor parameters.

#### What do you get instead?
`[ArgumentCountError] Too few arguments to function App\Entity\Thing::__construct(), 0 passed and at least 5 expected`

### Solution
In `Codeception\Util\ReflectionPropertyAccessor::setPropertiesForClass` check if the class has constructor parameters and if matching data is supplied, pass it as a parameter to the constructor. I'd be happy to provide you with a pull request for this change.

What do you think about this?

**Comment by alexkunin** [comment]
Right now this can be resolved by using `persistEntity`:

```php
$I->persistEntity(new \App\Entity\Thing($arg1, $arg2, ...), ['field1' => 'value', ...]);
```

In the future (PR #5624 has been merged into master already) same functionality will be baked into `haveInRepository`.

Your proposed solution actually sounds nice, very smart-DI-like (e.g. like Symfony's auto-wiring works), but also adds edge cases (e.g. parameter name matches field name, etc.), and also introduces lots of complexity. Not saying this will never be implemented (after all I'm not a maintainer), but current codebase already supports this feature as described above.

**Comment by burned42** [comment]
@alexkunin Thank you, I didn't know about `persistEntity()` :)

About the edge cases, you're actually right, that could be problematic and/or add complexity. For reference, this would be an implementation of what I thought about (without considering those edge cases): https://github.com/burned42/Codeception/tree/doctrine_haveInRepository_constructor_parameters

But since we can also pass an object to `persistEntity` and with your changes from the mentioned PR also to `haveInRepository()`, that's also fine for me, I'll just need to write my tests a bit different than expected :)

On the other side, I don't think that the changes from my linked branch would break any existing code because currently calling `haveInRepository` with a class that has a constructor with parameters just results in an exception, so I think it wouldn't hurt to merge even if there is a workaround (using `persistEntity`) and also even if there could be edge cases that would still not work (which wouldn't work with the current state either).

**Comment by alexkunin** [comment]
What I like about your approach is that we can just pass data to `haveInRepository` without actually calling constructor in our test, i.e. very declarative way. That... feels good, for some reason.

I almost agree with your other statement, except for the case when there are optional parameters with names matching fields: in this case user counts on constructor called with default values, and then fields are getting assigned, but with your change it will happen differently. Can't say if this is good or bad (need to see specific code), but this is certainly one of the edge cases I was talking about. Also, I'd say that having so much logic in constructor that might suffer from this little distinction sounds like a code smell. But, you know, people need to test things, even if things are not written according to today's best practices (legacy codebase etc.). That's why I'm trying to be careful here.

With that said, I would really like to see that functionality implemented. But it needs some handling of aforementioned edge cases, or maybe somewhat different approach (my own proposal was to use special field name, something like `__construct` -- it would work, but looks awkward, TBH).

And again, I'm not a maintainer, so maybe just go ahead and make a PR? @Naktibalda and @DavertMik might be able to add something to this idea to make it work.

**Comment by alexkunin** [comment]
I'm just thinking/brainstorming here, this is not a call for action.

We have edge case when there is optional parameter to constructor and field with the same name. Assumption that they mean the same in the context of particular entity could be valid or invalid, honestly we better assume they are totally different things with the same name.

One way to resolve this would be using a prefix for constructor parameters, e.g.:

```php
$I->haveInRepository(User::class, [
    '__construct.abcd' => 'value1',
    'abcd' => 'value2',
]);
```

A bit verbose (especially if constructor has many parameters), but very readable in my opinion. Also, that prefix might be optional, and if field matches argument, then:

- with `__construct.` prefix:
-- value is used in constructor
- without prefix:
-- if argument is optional, value is used for field assignment
-- if argument is required, value is used as constructor argument

I think this covers all possible cases? Syntax is not pretty, but it should be used only for that edge case anyway, we're just giving user opportunity to resolve name conflict without changing business code (the user might not be able to do that -- e.g. his assignment is to cover existing code with tests).

**Comment by alexkunin** [comment]
Or, we can assume that in case of name conflict user can just use the other way to specify constructor arguments described in https://github.com/Codeception/Codeception/issues/5632#issuecomment-518594241 above. In this case user looses ability to use declarative-only syntax, but I'm not sure if this is a real issue.
