### ISSUE TITLE
Incorrect coverage behavior with an abbreviated if form

### ISSUE THREAD

**Issue by pvsaintpe** [Codeception/Codeception#5653]
I have this class:

```php
class TestClass
{
    public function testMethod(bool $flag): int
    {
        $result = $flag === true
            ? 1
            : 0
        ;

        if ($flag === true) {
            $result = 1;
        } else {
            $result = 0;
        }

        return $result;
    }
}
```

**Case 1:**

And this Test:

```php
use Illuminate\Foundation\Testing\TestCase;

class TestClassTest extends TestCase
{
    public function testClass(): void
    {
        $testClass = new TestClass();
        $this->assertSame(0, $testClass->testMethod(false));
    }
}
```

php -d pcov.directory='.' vendor/bin/codecept run --coverage --coverage-html

Then I get this coverage report:
<img width="577" alt="Снимок экрана 2019-08-13 в 12 20 43" src="https://user-images.githubusercontent.com/16900171/62930337-e5e8f500-bdc4-11e9-83e3-a17a9057e455.png">

**Case 2:**

I modified my test:
```php
class TestClassTest extends TestCase
{
    public function testClass(): void
    {
        $testClass = new TestClass();
        $this->assertSame(1, $testClass->testMethod(true));
    }
}
```

Then I get this coverage report:
<img width="554" alt="Снимок экрана 2019-08-13 в 12 21 11" src="https://user-images.githubusercontent.com/16900171/62930415-0a44d180-bdc5-11e9-8623-6123dfee6a6f.png">

**Why?**

Why in the abbreviated form if code coverage does not work correctly?

* Codeception version: ^3.0
* PHP Version: 7.3.6
* Operating System: MacOS (Mojave)
* Installation type: composer

**Comment by Naktibalda** [comment]
It is an issue of your code coverage driver.
It looks like you are using pcov there.

**Comment by pvsaintpe** [comment]
> It is an issue of your code coverage driver.
> It looks like you are using pcov there.

I do not think, because I drove tests with both xdebug and phpdbg. Reports coverage generates a codeception, it is logical that he does it with errors.

**Comment by Naktibalda** [comment]
It isn't a long stretch to guess that xdebug and pcov has the same issue with ternary operator.
It could even be caused by the way php executes ternary operator.

Codeception does very little work in code coverage area - it handles command line parameters and calls php-code-coverage methods in the right places.
Coverage data is collected by xdebug or pcov and it is processed and HTML report is printed by [phpunit/php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage/) library.

https://github.com/Codeception/Codeception/blob/3.0.3/src/Codeception/Coverage/Subscriber/Printer.php#L37
https://github.com/Codeception/Codeception/blob/3.0.3/src/Codeception/Coverage/Subscriber/Printer.php#L103
