### ISSUE TITLE
seg fault while trying to terminate codeception process

### ISSUE THREAD

**Issue by strorch** [Codeception/Codeception#5845]
#### Hello! 
Testing my project and got a segmentation fault while trying to terminate codeception process.
All tests works good, but after pressing ^C got this error. 

```bash
- ContactsCest: Ensure i can create contact | {"first_name":"Test5e42d9629c378","last_nam...},"ru",{"country":"Algeria","client":"hipanel_test...}^C[1]    24165 segmentation fault (core dumped)  ./vendor/bin/codecept run acceptance
```

### Details

* Codeception version: 2.5.6
* PHP Version: php:7.4.2
* Operating System: Ubuntu 18.04
* Installation type: Composer
* ChromeDriver 80.0.3987.16
* openjdk version "1.8.0_242"

**Comment by Naktibalda** [comment]
Why are you using Codeception 2.5.6 on PHP 7.4? Upgrade to Codeception 4.

Anyway, segmentation fault is not caused by Codeception - it is caused by a bug in PHP or some PHP extension, please follow instructions on [this page](https://bugs.php.net/bugs-generating-backtrace.php) to investigate it.

**Comment by strorch** [comment]
Upgrading to Codeception 4 fixed this problem.
Maybe it caused by old facebook/webdriver package in old Codeception version.
Thank you!

**Comment by Naktibalda** [comment]
If you have time to spare and can reproduce the issue by downgrading Codeception, it would still be interesting to debug it.
It could be a bug in PHP 7.4.2 or one of extensions.

Here is an example of stacktrace which showed that particular segfault was caused by xdebug: https://bugs.xdebug.org/view.php?id=1246#c3415

**Comment by Fenikkusu** [comment]
I believe I actually ran into this issue already. I was trying to do some work with infection and codeception when I came across it. I believe it is something to do with the underlying symphony request. If you try to terminate it, the process does some final output. Since the pipe has already closed, it results in a segfault.
