### ISSUE TITLE
Sqlite DSN specification does not work with absolute paths

### ISSUE THREAD

**Issue by benr77** [Codeception/Codeception#5887]
#### What are you trying to achieve?

In the Db module, specify an Sqlite3 DSN that uses an absolute path.

#### What do you get instead?

```bash
In Db.php line 560:
                                                                                       
  [Codeception\Exception\ModuleException]                                              
  Db: SQLSTATE[HY000] [14] unable to open database file while creating PDO connection  
```

The problem I have found is that in the documentation for the Db module, it gives a link through to the Sqlite DSN documentation on PHP.net

https://codeception.com/docs/modules/Db#SQL-data-dump
https://www.php.net/manual/en/ref.pdo-sqlite.connection.php

The PHP documentation states that the syntax is

```
The DSN prefix is sqlite:.
To access a database on disk, append the absolute path to the DSN prefix.
```

The example given is `sqlite:/opt/databases/mydb.sq3`

However, what is not clear at all without poking in to the source of the Db module is that Codeception silently prefixes the project root path to the DSN filename. To get it to work in Codeception, you must use a relative file path - e.g. `sqlite:../../../../opt/databases/mydb.sq3` to get it to work.

What is the desired behaviour? If relative paths, as is currently the case, are expected, the documentation should state this as it's contrary to the specification on the PHP.net.

I would have thought Codeception should be able to detect an absolute path and use it if found, otherwise prefix the project dir to build an absolute path from the relative path as it does currently.

Happy to submit a PR if you agree with me.

### Details

* Codeception version: 4.1.1
* PHP Version: 7.4
* Operating System: Linux
* Installation type: Composer

**Comment by Naktibalda** [comment]
You are the first to raise this issue, Codeception has worked this way with sqlite files since [very beginning](https://github.com/Codeception/Codeception/commit/a81339aa298f572bda67c03f4c5518d8a51a4851#diff-1f52223992a2f828794b7311542aab73)

Sqlite DSN isn't mentioned in documentation of Db module at all and there are no examples.

I think that the reasons why the path is relative to project directory are:
a) Because it is quite common to store sqlite file in project directory.
b) It doesn't matter where your real database is, the tests usually run against test database which is cleared and reloaded from sql dump file for each test run, and that temporary file can be created in tests/data directory.

Starting to support absolute paths would be a backwards compatibility break and it would break tests for projects that currently have DB module with sqlite dsn starting with `/`.

**Comment by benr77** [comment]
> Sqlite DSN isn't mentioned in documentation of Db module at all and there are no examples.

This isn't quite true - there is a link to the PHP documentation for the Sqlite DSN syntax, which immediately refers to absolute paths.

Happy to not change the way Codeception works with a BC break, but I do think it would be worth making a note that the path is relative in the documentation.

**Comment by Naktibalda** [comment]
You are welcome to add a note about sqlite paths to the docblock at the top of https://github.com/Codeception/module-db/blob/master/src/Codeception/Module/Db.php

**Comment by benr77** [comment]
Done - see https://github.com/Codeception/module-db/pull/5
