### ISSUE TITLE
Commerce plugin not getting initialised in Unit testing 

### ISSUE THREAD

**Issue by chandamotiyani** [Codeception/Codeception#5981]
I'm writing unit tests for checking cart manipulations working on our site or not.
I went through https://github.com/craftcms/commerce/tree/develop/tests but in my CartTest.php file following function is throwing an exception not listing out the namespaces
 ```
protected function _before()
    {

        parent::_before();
        $this->cartController = new CartController('cart', Plugin::getInstance());
        $this->request = Craft::$app->getRequest();
        $this->request->enableCsrfValidation = false;
    }
```

  `[Error] Call to a member function getSettings() on null  `

Can you please describe or provide proper syntax of how to initialize the Plugin because the following not giving me any idea?

https://github.com/craftcms/cms/issues/1641

**Comment by Naktibalda** [comment]
This is a Craft CMS specific issue and it was resolved in https://github.com/craftcms/cms/issues/6878

**Comment by acalvino4** [comment]
When getting plugin instance from `setUpBeforeClass` in a unit test case, it seems that the plugin isn't registered yet:

```php
public static function setUpBeforeClass(): void {
    self::$pictureService = Plugin::getInstance()->picture;
}
```

throws `Attempt to read property "picture" on null at PictureTest.php:27`.

However, calling `getInstance()` within `_before` does work:

```php
public function _before(): void {
    self::$pictureService = Plugin::getInstance()->picture;
}
```

Is this expected behavior? It seems odd to me that plugin initialization would happen between these two method calls.
