### ISSUE TITLE
Drop the "part" architecture?

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#6026]
Before fixing https://github.com/Codeception/module-rest/pull/31#issuecomment-720945076 I'd like to question the "part" concept altogether:

What's the idea behind it? What's the advantage of loading only half of a module, instead of everything?

When keeping it as is, here are some docs issues I just stumbled upon (as a reminder):
* There appears to be an `email` part which is missing at https://codeception.com/docs/modules/Symfony#Parts, and at other email-related functions there.
* What does it mean that e.g. at https://codeception.com/docs/modules/REST#amBearerAuthenticated *both* parts are listed? That you'll get this method if you load part `json` or `xml` or the entire module (i.e. no `part` key given at all)? => This is inconsistent with https://codeception.com/docs/modules/Symfony where `part` is not mentioned for most functions.
* There should be a central "Parts" chapter somewhere, explaining how it works. And then, from every module page's "Parts" header, there should be a link to it.

**Comment by DavertMik** [comment]
I agree to the last point - a better documentation on a topic. If you know how to improve it that would help a lot!

The idea of parts was created due to the issues we faced when working with conflicting modules. Like Laravel5 & WebDriver.
We can't enable both modules - the behavior of amOnPage, click, etc will be unpredictable in this case.
However, we need only some part of Laravel like ORM to access database during WebDriver tests. Same for othres

**Comment by ThomasLandauer** [comment]
OK, I see. I'll try to come up with something - but I need more information:

1. Is the incompatibility always between WebDriver and something else? Or are there cases where the other modules are incompatible *among* each other?
2. Do all modules have parts? Where/how can I see this quickly?

**Comment by DavertMik** [comment]
1. Yes! All modules which have similary named methods do conflict with each other. When you call $I->click you must know for sure what will execute ot

2. Not all. Only framework modules + REST, I think.

**Comment by ThomasLandauer** [comment]
Yeah, OK, but nobody is going to use multiple framework modules in parallel, right?

So if we ignore REST for now, the "parts" situation is always: WebDriver + some framework, right?

REST: I'm always using the *entire* REST module, without any problems. So is there really a possible conflict between REST and any other module?
=> If the answer is NO, then I'd say: The central "Parts" chapter (from above) should be in WebDriver module.

**Comment by TavoNiievez** [comment]
> Yeah, OK, but nobody is going to use multiple framework modules in parallel, right?

I know of a use case in which it is possible to need to install at least 2 framework modules:
**It is** possible to use Eloquent within Symfony, and since there is no 'eloquent module' as there is a doctrine module, then, to test my repositories in my functional tests i would have to install the symfony module **and** the laravel module only with the ORM Part.

**Comment by ThomasLandauer** [comment]
OK, so after https://github.com/Codeception/module-webdriver/pull/33 is done, let's add a note about this in Symfony and/or Laravel chapter.

**Comment by ThomasLandauer** [comment]
Another question: What does `depends: Symfony` mean at https://codeception.com/docs/modules/Symfony#Parts? And is this the only usage of `depends`?

**Comment by Naktibalda** [comment]
Doctrine2 module is not independent, it requires collaboration from framework module in order to plug in to app execution.

Another module which depends on other modules to do the real work is REST.
