### ISSUE TITLE
`success` and `fail` characters (checkmark and "x") are displayed without color (i.e. grey)

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#6029]
Instead of a green ✔ and a red ✖, here's what the output looks like for me:
![Screenshot_20201103_164013](https://user-images.githubusercontent.com/1054469/98007399-a3f60580-1df3-11eb-84f7-10a12618c1ef.png)

These characters are already around since Codeception 2.4 https://github.com/Codeception/Codeception/blob/2.4/src/Codeception/Subscriber/Console.php#L104 - so my main question is: **Is anybody else observing this?**

I think this happened after upgrading from kubuntu 18.04 to 20.04. Looking closely at the screenshot, you can see that the characters are just rendered too large, and I'm guessing that this also prevents them from being colored.

**Comment by Naktibalda** [comment]
It is an issue of the terminal or font that you are using.

Since 2018 I run my tests on Ubuntu installed on WSL and I was using default Windows terminal application all this time and seeing broken Unicode chacters instead of unicode success and fail characters.

![image](https://user-images.githubusercontent.com/395992/103366918-72847800-4acc-11eb-8ed3-438eeeeb8c39.png)

Thanks to your question, I did some research and found [this article](https://blog.nillsf.com/index.php/2020/02/17/setting-up-wsl2-windows-terminal-and-oh-my-zsh/) which suggests to install different app called Windows Terminal.

Now I can see these characters:

![image](https://user-images.githubusercontent.com/395992/103367027-b7a8aa00-4acc-11eb-812e-74d79b44106a.png)

**Comment by ThomasLandauer** [comment]
It's in fact a bug in my terminal ("Konsole"): https://bugs.kde.org/show_bug.cgi?id=349088

**Comment by Naktibalda** [comment]
@ThomasLandauer Is there anything wrong with default `+` and 'x' characters that are used in `no-ansi` mode?

You get them if you use  `codecept run --no-ansi`. Is is to cumbersome to use additional parameter?

**Comment by ThomasLandauer** [comment]
Well, this removes *all* color from the output, so it's even worse than with the misrendered symbols ;-)

**Comment by Naktibalda** [comment]
Try `--no-ansi --colors` combination.
