### ISSUE TITLE
Empty report.json file generated when no test/scenario has run

### ISSUE THREAD

**Issue by unki** [Codeception/Codeception#6041]
I've noticed that when _codecept-run_ is called with `--json=report.json` parameter on a run which - for some reason - is not actually performing any test/scenario, it will generate an empty _report.json_ file (filesize = 0).

On the other hand `--html=report.html` in the same situation _will_ produce a complete HTML-report - but obviously in there then stating that no scenarios have been performed.

I know that I could easily check if _report.json_ is empty or not :)
But may it be better to have some consistent behavior here?

e.g. instead of an empty _report.json_ file _Codeception_ could just write `[]` or `{}` into _report.json_ - then it would be at least JSON-syntactically valid.

The zero-sized _report.json_ would make me believe something went horribly wrong (e.g. exception thrown or so) - what could have left back an incomplete _report.json_ as a residue. In such cases where I wouldn't have checked  _Codeception's_ output or generated a HTML-report too.

```
bash-5.0$ ls -lrt tests/_output/
total 8
-rw-rw-r-- 1 1000 1000 6863 Nov 29 07:24 report.html
-rw-rw-r-- 1 1000 1000    0 Nov 29 07:44 report.json
```

ps: tested with `v4.1.7`

**Comment by Naktibalda** [comment]
I looked into this.

The difference between [JSON](https://github.com/Codeception/phpunit-wrapper/blob/9.0.5/src/phpunit5-loggers.php#L257-L262) and [HTML](https://github.com/Codeception/phpunit-wrapper/blob/9.0.5/src/ResultPrinter/HTML.php#L193-L230) is that JSON logger writes to file in `endTestSuite` method and HTML writes in `endRun`.
So, I guess, when there are no matching tests, `endTestSuite` is not executed.

The obvious fix of adding `endRun` method to JSON class doesn't work, because it extends different parent class, which doesn't call endRun method.

JSON extends \PHPUnit\Util\Printer,
HTML indirectly extends [\PHPUnit\Util\TestDox\ResultPrinter](https://github.com/sebastianbergmann/phpunit/blob/9.5.0/src/Util/TestDox/ResultPrinter.php#L123).

JSON and TAP reporters originally were a feature of PHPUnit, but they were removed from PHPUnit 6.0 and Codeception copied their code to keep the functionality.

TestListener interface was deprecated 2 years ago and a lot of relevant code is being removed right now, so it is very likely that signifficant effor will be required to keep reports working with PHPUnit 10.

**Comment by Naktibalda** [comment]
PHPUnit 10 really breaks all report functionality, I may fix this issue when (if) I get it working again.

**Comment by Naktibalda** [comment]
JSON report format was removed in Codeception 5.0

**Comment by MahmoodKhalil57** [comment]
What? Why was JSON report format removed from codeception? Im currently parsing the html report to generate a json report which adds unnecessary steps

**Comment by Naktibalda** [comment]
@MahmoodKhalil57 Because it required a lot of work to rewrite features hardly used by anyone.

You can implement your own reporter as Codeception extension. See this little section of documentation: https://codeception.com/docs/Reporting#Custom-Reporter
