### ISSUE TITLE
`wantTo()` is not documented

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#6076]
Just noticed that `wantTo()` (and probably similar functions like `expect()`, `comment()` etc.) are not really documented - the only occurrence I found is https://codeception.com/docs/06-ReusingTestCode#What-are-Actors

What's the purpose of all these? The only one I'm (mis)using sometimes is `wantTo` to get a comment. But this isn't working in unit tests - see https://github.com/Codeception/Codeception/issues/6075. So besides not knowing what the *content* of an explanation could be, I don't even know what a proper *location* would be ;-)

**Comment by Naktibalda** [comment]
There is a short `Comments` section in Acceptance testing page: https://codeception.com/docs/03-AcceptanceTests

**Comment by ThomasLandauer** [comment]
That says:

> Within a long scenario, you should describe what actions you are going to perform and what results should be achieved. Comment methods like amGoingTo, expect, expectTo help you in making tests more descriptive:

My question is: If I want to make my tests "more descriptive", I add a PHP comment ;-) So what's the advantage of all those methods? Is the stuff you write in there even displayed anywhere? Where? The only thing I know is `wantTo()`, see https://github.com/Codeception/Codeception/issues/6075#issue-780734106

Who created those methods and what was the original idea?

**Comment by Naktibalda** [comment]
Run your functional or acceptance tests with `--steps` parameter.

**Comment by ThomasLandauer** [comment]
Oh, thanks! But what's the reason for having so many? I mean, those two produce the same output:
```php
$I->expectTo('foo');
$I->expect('to foo');
```
So why not replace them all by a general-purpose `say()`?
```php
$I->say('I expect to foo');
```
Or are those *different* methods needed by Gherkin or something?

**Comment by DavertMik** [comment]
@ThomasLandauer 

Yes, methods are the same but because of autocompletion it is easier to build phrases using different methods. 
So If I think my line starts with `expect to` I pick I->expectTo
If it is something different, I pick `I->expect`

The only problem I see here that users expect that expect==assert. Which is a bit confusing

---

About `wantTo`, here is tht thing.
This is legacy command that should be used solely for Cept scenarios.
In Cept this was the way you set a name for a test - it is the most consistent approach.

In Cest you can set name from a method name so I don't see any reason using wantTo. That's why it is hidden from documentation as well as everything related to Cept format. It stays in codebase for BC reasons

**Comment by ThomasLandauer** [comment]
I opened a discussion for this: https://github.com/Codeception/Codeception/discussions/6146
