### ISSUE TITLE
Path and Branch coverage setting

### ISSUE THREAD

**Issue by s0lus** [Codeception/Codeception#6155]
Hey!

php-code-coverage and xdebug introduced new metrics for code coverage - path and branch coverage. 
I want to enable them, but currently I can't. Because I don't see any information in documentation or setting in the configuration file how to do that.

More information about path and branch coverage: [php-code-coverage issue](https://github.com/sebastianbergmann/php-code-coverage/issues/380), [article from contributor](https://doug.codes/php-code-coverage).

I quickly walked through codebase, and it's looks like it shouldn't too difficult to added that. Can I contribute to add this feature?

**Comment by Naktibalda** [comment]
You are welcome to implement this feature.

The way php-code-coverage is initialized keeps changing. so it is the best to implement it in 5.0 branch and probably even in 5.0-phpunit-10 branch to support both PHPUnit 9 and 10.

https://github.com/Codeception/Codeception/blob/5.0-phpunit-10/src/Codeception/Coverage/PhpCodeCoverageFactory.php#L20-L25

You have to make second parameter of `PHPUnitCodeCoverage::activate($filter, false);` configurable and add `if` statement to call `forLineAndPathCoverage` instead of `forLineCoverage`.

While you are there, please replace deprecated `$driver = Driver::forLineCoverage($filter);` with

```php
use SebastianBergmann\CodeCoverage\Driver\Selector;

$driver = (new Selector)->forLineCoverage($filter),
```

I think that for consistency with other coverage settings, new setting should be named `path_coverage` and added to https://github.com/Codeception/Codeception/blob/5.0-phpunit-10/src/Codeception/Coverage/SuiteSubscriber.php#L40

Please update some tests in `tests/coverage` to test branch coverage.

The final step will be to document this setting in https://github.com/Codeception/codeception.github.com/blob/master/docs/11-Codecoverage.md

**Comment by s0lus** [comment]
@Naktibalda can you review it please? https://github.com/Codeception/Codeception/pull/6158

Also, I have a question about documentation. Should I already start to work for PR to documentation repository, or I need to wait until this feature will be merged?

**Comment by Naktibalda** [comment]
Thanks, I merged your PR. I can't give you release date of Codeception 5.0 yet, but it should be released in the next few months.

It would be great if you could raise documentation pull request.

**Comment by s0lus** [comment]
> Thanks, I merged your PR.

@Naktibalda ❤️ 

> It would be great if you could raise documentation pull request.

Yes, I will submit a pull request. If you don't mind I will leave this issue open for reference from documentation repo.

**Comment by Naktibalda** [comment]
This feature was released in 5.0.0-alpha1

**Comment by Lewiscowles1986** [comment]
How can I disabled path coverage? I'm working in a codebase where every single line is green and path coverage is 0%. I Don't understand it, but I'm interested in just outputting line and branch coverage until this is remediated.

**Comment by Naktibalda** [comment]
What's the difference between path coverage and branch coverage?

Are you using Codeception 5?

**Comment by Lewiscowles1986** [comment]
The repo I was looking at does not, but we have another one which does use codeception;
