### ISSUE TITLE
Behat/Gherkin PyString requires arg in step pattern

### ISSUE THREAD

**Issue by guilliamxavier** [Codeception/Codeception#6432]
#### What are you trying to achieve?

Migrate from Behat to Codeception. But steps with PyString are not handled correctly. Example:

- in feature file:

```gherkin
  Scenario: Test
    When I say "one two"
    Then I should see:
      """
      one
      two
      """
```

- in context class:

```php
    /**
     * @When I say :line
     */
    public function iSay($line): void
    {
        var_dump($line);
    }

    /**
     * @Then I should see:
     */
    public function iShouldSee($text): void
    {
        var_dump($text);
    }
```

Expected result *(as working with Behat without Codeception)*:

```
string(7) "one two"
object(Behat\Gherkin\Node\PyStringNode)#304 (2) {
  ["strings":"Behat\Gherkin\Node\PyStringNode":private]=>
  array(2) {
    [0]=>
    string(3) "one"
    [1]=>
    string(3) "two"
  }
  ["line":"Behat\Gherkin\Node\PyStringNode":private]=>
  int(6)
}
```

#### What do you get instead?

```
Step definition for `I should see: ""` not found in contexts
Run gherkin:snippets to define missing steps
```

and proposes snippet:

```
    /**
     * @Then I should see: :arg1
     */
     public function iShouldSee($arg1)
     {
         throw new \PHPUnit\Framework\IncompleteTestError("Step `I should see: :arg1` is not defined");
     }
```

(note the "I should see: **:arg1**") which indeed works with Codeception but deviates from standard Behat.

### Details

* Codeception version: 4.1.31
* PHP Version: 7.4
* Operating System: Ubuntu 20.04
* Installation type: Composer
* List of installed packages (`composer show`)
  - behat/behat v3.10.0
  - behat/gherkin v4.9.0
  - behatch/contexts 3.3.0

Related: #4125

**Comment by Naktibalda** [comment]
Does it work as expected if you change your test to `@Then I should see: ""` ?

**Comment by Naktibalda** [comment]
I won't fix this issue, but if anyone wants to try I will give a few hints.

Gherkin support is all about pattern matching. Codeception only supports steps with single named parameter.

To support steps without named parameters at least two changes are necessary:

1. Update [Codeception\Test\Gherkin::runStep](https://github.com/Codeception/Codeception/blob/5.0.0-RC2/src/Codeception/Test/Gherkin.php#L162-L180) to match steps with and without named parameter when step has pystring.

2. It may be necessary to update [Codeception\Test\Loader\Gherkin::makePlaceholderPattern](https://github.com/Codeception/Codeception/blob/5.0.0-RC2/src/Codeception/Test/Loader/Gherkin.php#L152-L175) to match trailing colon.

Note: We may have to make major changes in Gherkin support when behat/gherkin is replaced with [cucumber/gherkin](https://github.com/cucumber/gherkin-php) in a year or two (Probably in Codeception 6,  because cucumber/gherkin requires PHP 8.1).

**Comment by succinct** [comment]
This issue has bitten me too. I have dozens of feature files written using the Gherkin docstring/PyString syntax which are now breaking.
