### ISSUE TITLE
The generated TryTo* function does not have a return statement

### ISSUE THREAD

**Issue by lonesoft** [Codeception/Codeception#6559]
#### What are you trying to achieve?
Use the TryTo step decorator to check some condition

#### What do you get instead?
The generated TryTo* function does not have a return statement

> Expected:

```php
    public function tryToSeeElement($selector, array $attributes = []): bool {
        return $this->getScenario()->runStep(new \Codeception\Step\TryTo('seeElement', func_get_args()));
    }
```
> Actual:

```php
    public function tryToSeeElement($selector, array $attributes = []): void {
        $this->getScenario()->runStep(new \Codeception\Step\TryTo('seeElement', func_get_args()));
    }
```
### Details

* Codeception version: 5.0.1
* PHP Version: 8.1.8
* Operating System: Windows WSL/ubuntu

**Comment by Naktibalda** [comment]
There is no promise that TryTo decorator makes method return different type as original.

`seeElement` has return type `void`, so `tryToSeeElement` has the same type.

**Comment by lonesoft** [comment]
Thank you for the comment. I see your point.
However the `TryTo` by itself returns `true`/`false`, basked on the fact the the Action succeeded or not.
The only way to achieve, say, `tryToSeeElement` is to wrap `seeElement` around a `Try`/`Catch`, which is exactly what the `TryTo` does
So, I would like to suggest the following:
* if the Action (e.g. grab... execute... etc.) **does** return a value, we can simply return that value
* if the Action (e.g. `seeElement`) **does not** return any value, the generated code for `tryTo...` should return `true`/`false` based on the success of Action, i.e. if it does not throw

**Comment by chris-miller-jonah** [comment]
The documentation for  Acceptance testing for WebDriver for A/B Testing says that calling tryToSeeElement should return true/false so that tests can use this in an IF/ELSE type of situation. This worked in previous version(s) of Codeception and now has broken existing tests written prior to Codeception 5.x.

**Comment by Naktibalda** [comment]
Alright, I understand the problem now.

`tryTo` stopped returning `true/false` when `void` return type was declared for `seeElement` method in https://github.com/Codeception/module-webdriver/commit/f297164d057e6b401f65dfe253ad59d7231b0e4d.

It happens because `tryTo` decorator copies method template from original action and doesnt override `return` and `return_type` variables in https://github.com/Codeception/Codeception/blob/3f4991df28131b6e0a7076c5dd02f8176f9aebbc/src/Codeception/Step/TryTo.php#L46-L49
