### ISSUE TITLE
Installation - Wrong Instructions On Command Line To Generate Test

### ISSUE THREAD

**Issue by benanamen** [Codeception/Codeception#6644]
#### What are you trying to achieve?
Create the first acceptance test after bootstrapping Codeception.

#### What do you get instead?
After completion of running the bootstrap command "Next Step" instructions 1-4 are displayed. Instructions 3 & 4 are wrong.

3. Create your first acceptance tests using ```codecept g:cest acceptance First```
4. Write first test in **tests/acceptance/FirstCest.php**

The bootstrap creates directories tests/Acceptance with a CAPITAL A in Acceptance, not lowercase. If you try to run the instruction as shown (copy/paste) you will get the error: "Suite acceptance was not loaded"

FIX: "Next Step" instructions need the "a" in "_acceptance_" in Steps 3 & 4  changed to Uppercase "A"

FILE: codeception/codeception/src/Codeception/Template/Bootstrap.php
LINES: 72 & 73

### Details

* Codeception version: 5x
* PHP Version: 8.1
* Operating System: Any

**Comment by covovker** [comment]
True. Simply following the instructions in "getting started" section just does not work. It fails on the attempt to generate any test in the example, because the example has lowercase suit names. Following the example 
`codecept generate:test unit Example`
produces an error:
```
In Configuration.php line 338:                             
  Suite unit was not loaded  
```
                             
Capital "U" fixes the problem. Although it took some time and googling to figure that out.

**Comment by mandrasch** [comment]
+1, ran into this today as well while following https://codeception.com/docs/APITesting :)
