### ISSUE TITLE
@depends issues

### ISSUE THREAD

**Issue by Phil-Barker** [Codeception/Codeception#903]
Unless I'm missing something the @depends syntax doesn't seem to work in Tests

```
public function test1()
{
    // asserting tests here
    return $object;
}

/**
 * @depends test1
 */
public function test2($object)
{
    // more tests here
}
```

test1 runs - and all the tests below number 2 run but test2 never runs.
Have I missed something or is the @depends logic not running correctly?

**Comment by Fuin** [comment]
So I was looking through this issue and I was wondering if the @depends annotation now works with the return statement

Because for my tests I want to pass a cookie Object only between two tests, rather than setting it in a Variable for the whole class. 

`    public function rememberMyLogin(\Step\Acceptance\Login $I)
    {
       
        $I->amOnPage(HomePage::$URL);
        $I->openLoginLayer();
        $I->waitForElementVisible(LoginPage::$loginEmailField);
        $I->fillField(LoginPage::$loginEmailField, 'email@email.com');
        $I->fillField(LoginPage::$loginPasswordField, 'Password');
        $I->click(LoginPage::$loginMemorizePasswordCheckbox);
        $I->click(LoginPage::$loginSignInButton);
        $I->waitForElementVisible(ProfilePage::$profileContactDataLink);
        $I->waitForAllModulesLoaded();
        $I->seeCookie('remember_me');
        $I->amOnUrl($URL);
        $I->amOnUrl(HomePage::$URL);
        $I->waitForElementVisible(ProfilePage::$profileHeadline);
        $I->see('Profile');
        $I->seeCookie('remember_me');
        $cookie = $I->grabCookie('remember_me');
        return $cookie;
    }

    /**
     * @param \Step\Acceptance\Login $I
     *
     * @depends rememberMyLogin
     * @depends ProfileManagement\RegistrationCest:registerWithRequiredFields
     */
    public function rememberMyLogin2(\Step\Acceptance\Login $I, $cookie)
    {
        $I->wantTo('test if I am still logged in after restart the browser');
        $I->setCookie('remember_me', $cookie);
        $I->amOnPage(HomePage::$URL);
        $I->waitForElementVisible(ProfilePage::$profileHeadline);
        $I->see('Data');
    } `

but for the second test I get an error message stating `[Facebook\WebDriver\Exception\UnknownServerException] java.util.HashMap cannot be cast to java.lang.String`
And in the steps it says 
`$I->setCookie("remember_me","Codeception\\Scenario")`

Is it right that @depends cant pass objects between two tests and is there any way to work around this now?
